export interface Product {
  id: string;
  name: string;
  slug: string;
  sku: string;
  description: string;
  shortDescription: string;
  brand: string | null;
  brandSlug: string | null;
  category: string;
  categorySlug: string;
  subCategory: string | null;
  subCategorySlug: string | null;
  unit: string;
  unitCode: string;
  unitSymbol: string | null;
  price: number;
  mrp: number;
  discount: number;
  bulkPrice: number | null;
  bulkMinQty: number | null;
  bulkLabel: string | null;
  gstRate: number;
  gstCode: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  stockLevel: number;
  moq: number;
  deliveryDays: number;
  freeDelivery: boolean;
  seller: { name: string; rating: number; isVerified: boolean };
  images: string[];
  specifications: Record<string, string>;
  features: string[];
  tags: string[];
}

export interface Category {
  name: string;
  slug: string;
  description: string;
  icon: string;
  productCount: number;
  subCategories: { name: string; slug: string; productCount: number }[];
}

export const categories: Category[] = [
  { name: "Cement", slug: "cement", description: "OPC, PPC, Ready Mix", icon: "cement", productCount: 10, subCategories: [
    { name: "OPC Cement", slug: "opc", productCount: 3 },
    { name: "PPC Cement", slug: "ppc", productCount: 4 },
    { name: "Ready Mix", slug: "ready-mix", productCount: 3 },
  ]},
  { name: "Painting", slug: "painting", description: "Paints, Primers, Putty", icon: "paint", productCount: 34, subCategories: [
    { name: "Exterior Paint", slug: "exterior", productCount: 5 },
    { name: "Interior Paint", slug: "interior", productCount: 5 },
    { name: "Primer", slug: "primer", productCount: 6 },
    { name: "Putty", slug: "putty", productCount: 5 },
    { name: "Enamel", slug: "enamel", productCount: 3 },
    { name: "Accessories", slug: "accessories", productCount: 10 },
  ]},
  { name: "Lighting", slug: "lighting", description: "LED, Downlights, Strip Lights", icon: "lighting", productCount: 17, subCategories: [
    { name: "LED Downlight", slug: "downlight", productCount: 5 },
    { name: "Strip Light", slug: "strip", productCount: 3 },
    { name: "Tube Light", slug: "tube", productCount: 2 },
    { name: "COB Light", slug: "cob", productCount: 3 },
    { name: "Rope Light", slug: "rope", productCount: 2 },
    { name: "Accessories", slug: "accessories", productCount: 2 },
  ]},
  { name: "Tiling", slug: "tiling", description: "Adhesives, Waterproofing", icon: "tiles", productCount: 14, subCategories: [
    { name: "Adhesive", slug: "adhesive", productCount: 8 },
    { name: "Waterproofing", slug: "waterproofing", productCount: 4 },
    { name: "Grout", slug: "grout", productCount: 2 },
  ]},
];

export const products: Product[] = [
  // ═══════════════════════════════════════════════════════════════
  // CEMENT (10 products)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "cement-acc", name: "ACC Cement 50kg", slug: "acc-cement-50kg", sku: "CEM-ACC-50",
    description: "ACC Cement 50kg bag for general construction, plastering, and masonry work.",
    shortDescription: "PPC cement for general construction",
    brand: "ACC", brandSlug: "acc", category: "Cement", categorySlug: "cement",
    subCategory: "PPC Cement", subCategorySlug: "ppc",
    unit: "Bag (50 kg)", unitCode: "BAG", unitSymbol: null,
    price: 370, mrp: 400, discount: 8, bulkPrice: 350, bulkMinQty: 50, bulkLabel: "₹350 at 50+ bags",
    gstRate: 28, gstCode: "GST 28%", rating: 4.6, reviewCount: 2100,
    inStock: true, stockLevel: 5000, moq: 10, deliveryDays: 1, freeDelivery: true,
    seller: { name: "ACC Cement Dealers", rating: 4.6, isVerified: true },
    images: ["/products/cement/ACC Cement.png"],
    specifications: { "Grade": "PPC", "Weight": "50 kg" },
    features: ["High quality", "ISI marked", "Fly ash based"],
    tags: ["cement", "ppc", "acc"],
  },
  {
    id: "cement-ambuja", name: "Ambuja Cement 50kg", slug: "ambuja-cement-50kg", sku: "CEM-AMB-50",
    description: "Ambuja Cement 50kg bag. Trusted brand for durable construction.",
    shortDescription: "Trusted PPC cement for lasting strength",
    brand: "Ambuja", brandSlug: "ambuja", category: "Cement", categorySlug: "cement",
    subCategory: "PPC Cement", subCategorySlug: "ppc",
    unit: "Bag (50 kg)", unitCode: "BAG", unitSymbol: null,
    price: 365, mrp: 395, discount: 8, bulkPrice: 345, bulkMinQty: 50, bulkLabel: "₹345 at 50+ bags",
    gstRate: 28, gstCode: "GST 28%", rating: 4.5, reviewCount: 1800,
    inStock: true, stockLevel: 5000, moq: 10, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Ambuja Cement Dealers", rating: 4.5, isVerified: true },
    images: ["/products/cement/Ambuja Cement.png"],
    specifications: { "Grade": "PPC", "Weight": "50 kg" },
    features: ["Trusted brand", "ISI marked", "Consistent quality"],
    tags: ["cement", "ppc", "ambuja"],
  },
  {
    id: "cement-dalmia", name: "Dalmia Cement 50kg", slug: "dalmia-cement-50kg", sku: "CEM-DAL-50",
    description: "Dalmia Cement 50kg bag. Cost-effective cement for everyday construction.",
    shortDescription: "Value cement for general use",
    brand: "Dalmia", brandSlug: "dalmia", category: "Cement", categorySlug: "cement",
    subCategory: "PPC Cement", subCategorySlug: "ppc",
    unit: "Bag (50 kg)", unitCode: "BAG", unitSymbol: null,
    price: 355, mrp: 385, discount: 8, bulkPrice: 335, bulkMinQty: 50, bulkLabel: "₹335 at 50+ bags",
    gstRate: 28, gstCode: "GST 28%", rating: 4.5, reviewCount: 1500,
    inStock: true, stockLevel: 5000, moq: 10, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Dalmia Cement Dealers", rating: 4.4, isVerified: true },
    images: ["/products/cement/Dalmia Cement.png"],
    specifications: { "Grade": "PPC", "Weight": "50 kg" },
    features: ["Cost effective", "ISI marked", "Good workability"],
    tags: ["cement", "ppc", "dalmia"],
  },
  {
    id: "cement-jklakshmi", name: "JK Lakshmi Pro+ Cement 50kg", slug: "jk-lakshmi-pro-cement-50kg", sku: "CEM-JKL-50",
    description: "JK Lakshmi Pro+ Cement 50kg. Premium cement with enhanced strength.",
    shortDescription: "Premium cement with enhanced strength",
    brand: "JK Lakshmi", brandSlug: "jk-lakshmi", category: "Cement", categorySlug: "cement",
    subCategory: "OPC Cement", subCategorySlug: "opc",
    unit: "Bag (50 kg)", unitCode: "BAG", unitSymbol: null,
    price: 360, mrp: 390, discount: 8, bulkPrice: 340, bulkMinQty: 50, bulkLabel: "₹340 at 50+ bags",
    gstRate: 28, gstCode: "GST 28%", rating: 4.6, reviewCount: 1700,
    inStock: true, stockLevel: 5000, moq: 10, deliveryDays: 1, freeDelivery: true,
    seller: { name: "JK Lakshmi Dealers", rating: 4.6, isVerified: true },
    images: ["/products/cement/JK Lakshmi Pro Cement.png"],
    specifications: { "Grade": "OPC 53", "Weight": "50 kg" },
    features: ["Pro+ formula", "High early strength", "ISI marked"],
    tags: ["cement", "opc", "jk-lakshmi"],
  },
  {
    id: "cement-jksuper", name: "JK Super Cement 50kg", slug: "jk-super-cement-50kg", sku: "CEM-JKS-50",
    description: "JK Super Cement 50kg. Reliable cement for residential construction.",
    shortDescription: "Reliable cement for homes",
    brand: "JK Super", brandSlug: "jk-super", category: "Cement", categorySlug: "cement",
    subCategory: "PPC Cement", subCategorySlug: "ppc",
    unit: "Bag (50 kg)", unitCode: "BAG", unitSymbol: null,
    price: 350, mrp: 380, discount: 8, bulkPrice: 330, bulkMinQty: 50, bulkLabel: "₹330 at 50+ bags",
    gstRate: 28, gstCode: "GST 28%", rating: 4.4, reviewCount: 1400,
    inStock: true, stockLevel: 5000, moq: 10, deliveryDays: 1, freeDelivery: true,
    seller: { name: "JK Super Dealers", rating: 4.4, isVerified: true },
    images: ["/products/cement/JK Super Cement.png"],
    specifications: { "Grade": "PPC", "Weight": "50 kg" },
    features: ["Reliable quality", "ISI marked", "Good bonding"],
    tags: ["cement", "ppc", "jk-super"],
  },
  {
    id: "cement-jsw", name: "JSW Cement 50kg", slug: "jsw-cement-50kg", sku: "CEM-JSW-50",
    description: "JSW Cement 50kg. Premium quality cement with advanced technology.",
    shortDescription: "Premium cement with advanced tech",
    brand: "JSW", brandSlug: "jsw", category: "Cement", categorySlug: "cement",
    subCategory: "PPC Cement", subCategorySlug: "ppc",
    unit: "Bag (50 kg)", unitCode: "BAG", unitSymbol: null,
    price: 365, mrp: 395, discount: 8, bulkPrice: 345, bulkMinQty: 50, bulkLabel: "₹345 at 50+ bags",
    gstRate: 28, gstCode: "GST 28%", rating: 4.5, reviewCount: 1600,
    inStock: true, stockLevel: 5000, moq: 10, deliveryDays: 1, freeDelivery: true,
    seller: { name: "JSW Cement Dealers", rating: 4.5, isVerified: true },
    images: ["/products/cement/JSW Cement.png"],
    specifications: { "Grade": "PPC", "Weight": "50 kg" },
    features: ["Advanced technology", "ISI marked", "Green cement"],
    tags: ["cement", "ppc", "jsw"],
  },
  {
    id: "cement-mpbirla", name: "MP Birla Samrat Cement 50kg", slug: "mp-birla-samrat-cement-50kg", sku: "CEM-MPB-50",
    description: "MP Birla Samrat Cement 50kg. High-performance cement for structural applications.",
    shortDescription: "High-performance structural cement",
    brand: "MP Birla", brandSlug: "mp-birla", category: "Cement", categorySlug: "cement",
    subCategory: "OPC Cement", subCategorySlug: "opc",
    unit: "Bag (50 kg)", unitCode: "BAG", unitSymbol: null,
    price: 355, mrp: 385, discount: 8, bulkPrice: 335, bulkMinQty: 50, bulkLabel: "₹335 at 50+ bags",
    gstRate: 28, gstCode: "GST 28%", rating: 4.5, reviewCount: 1300,
    inStock: true, stockLevel: 5000, moq: 10, deliveryDays: 1, freeDelivery: true,
    seller: { name: "MP Birla Dealers", rating: 4.4, isVerified: true },
    images: ["/products/cement/MP Birla Samrat Cement.png"],
    specifications: { "Grade": "OPC 53", "Weight": "50 kg" },
    features: ["High performance", "ISI marked", "Structural grade"],
    tags: ["cement", "opc", "mp-birla"],
  },
  {
    id: "cement-shree", name: "Shree Cement 50kg", slug: "shree-cement-50kg", sku: "CEM-SHR-50",
    description: "Shree Cement 50kg. Economical cement with consistent quality.",
    shortDescription: "Economical cement with consistent quality",
    brand: "Shree", brandSlug: "shree", category: "Cement", categorySlug: "cement",
    subCategory: "PPC Cement", subCategorySlug: "ppc",
    unit: "Bag (50 kg)", unitCode: "BAG", unitSymbol: null,
    price: 360, mrp: 390, discount: 8, bulkPrice: 340, bulkMinQty: 50, bulkLabel: "₹340 at 50+ bags",
    gstRate: 28, gstCode: "GST 28%", rating: 4.5, reviewCount: 1500,
    inStock: true, stockLevel: 5000, moq: 10, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Shree Cement Dealers", rating: 4.5, isVerified: true },
    images: ["/products/cement/Shree Cement.png"],
    specifications: { "Grade": "PPC", "Weight": "50 kg" },
    features: ["Economical", "Consistent quality", "ISI marked"],
    tags: ["cement", "ppc", "shree"],
  },
  {
    id: "cement-ultratech", name: "UltraTech Cement 50kg", slug: "ultratech-cement-50kg", sku: "CEM-UT-50",
    description: "UltraTech Cement 50kg. India's largest cement brand for superior construction.",
    shortDescription: "India's largest cement brand",
    brand: "UltraTech", brandSlug: "ultratech", category: "Cement", categorySlug: "cement",
    subCategory: "OPC Cement", subCategorySlug: "opc",
    unit: "Bag (50 kg)", unitCode: "BAG", unitSymbol: null,
    price: 385, mrp: 410, discount: 6, bulkPrice: 365, bulkMinQty: 50, bulkLabel: "₹365 at 50+ bags",
    gstRate: 28, gstCode: "GST 28%", rating: 4.7, reviewCount: 2500,
    inStock: true, stockLevel: 5000, moq: 10, deliveryDays: 1, freeDelivery: true,
    seller: { name: "UltraTech Cement Dealers", rating: 4.7, isVerified: true },
    images: ["/products/cement/Ultratech Cement.png"],
    specifications: { "Grade": "OPC 53", "Weight": "50 kg" },
    features: ["India's largest brand", "High early strength", "ISI marked"],
    tags: ["cement", "opc", "ultratech"],
  },
  {
    id: "cement-wonder", name: "Wonder Cement 50kg", slug: "wonder-cement-50kg", sku: "CEM-WON-50",
    description: "Wonder Cement 50kg. Quality cement at competitive prices.",
    shortDescription: "Quality cement at competitive prices",
    brand: "Wonder", brandSlug: "wonder", category: "Cement", categorySlug: "cement",
    subCategory: "PPC Cement", subCategorySlug: "ppc",
    unit: "Bag (50 kg)", unitCode: "BAG", unitSymbol: null,
    price: 345, mrp: 375, discount: 8, bulkPrice: 325, bulkMinQty: 50, bulkLabel: "₹325 at 50+ bags",
    gstRate: 28, gstCode: "GST 28%", rating: 4.4, reviewCount: 1200,
    inStock: true, stockLevel: 5000, moq: 10, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Wonder Cement Dealers", rating: 4.3, isVerified: true },
    images: ["/products/cement/Wonder Cement.png"],
    specifications: { "Grade": "PPC", "Weight": "50 kg" },
    features: ["Competitive price", "ISI marked", "Good quality"],
    tags: ["cement", "ppc", "wonder"],
  },

  // ═══════════════════════════════════════════════════════════════
  // PAINTING (34 products)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "paint-asian-apex", name: "Asian Paints Apex, Base White", slug: "asian-paints-apex-base-white", sku: "PNT-AP-APX",
    description: "Asian Paints Apex exterior emulsion for weather protection.",
    shortDescription: "Exterior weather-proof emulsion",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Exterior Paint", subCategorySlug: "exterior",
    unit: "Can (20 L)", unitCode: "CAN", unitSymbol: null,
    price: 2400, mrp: 3100, discount: 23, bulkPrice: 2200, bulkMinQty: 5, bulkLabel: "₹2200 at 5+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.6, reviewCount: 4230,
    inStock: true, stockLevel: 500, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.7, isVerified: true },
    images: ["/products/painting/Asian Paints Apex, Base White.png"],
    specifications: { "Type": "Exterior Emulsion", "Size": "20 L", "Finish": "Matt" },
    features: ["Weather proof", "Anti-fungal", "Low VOC"],
    tags: ["paint", "exterior", "asian-paints", "apex"],
  },
  {
    id: "paint-asian-royale", name: "Asian Paints Royale Luxury Emulsion", slug: "asian-paints-royale-luxury-emulsion", sku: "PNT-AP-ROY",
    description: "Asian Paints Royale Luxury Emulsion for premium interior walls.",
    shortDescription: "Premium interior luxury emulsion",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Interior Paint", subCategorySlug: "interior",
    unit: "Can (20 L)", unitCode: "CAN", unitSymbol: null,
    price: 3200, mrp: 4000, discount: 20, bulkPrice: 3000, bulkMinQty: 5, bulkLabel: "₹3000 at 5+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.7, reviewCount: 3100,
    inStock: true, stockLevel: 300, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.7, isVerified: true },
    images: ["/products/painting/Asian Paints Royale Luxury Emulsion, Base White.png"],
    specifications: { "Type": "Interior Emulsion", "Size": "20 L", "Finish": "Silk" },
    features: ["Luxury finish", "Stain resistant", "Low odour"],
    tags: ["paint", "interior", "asian-paints", "royale"],
  },
  {
    id: "paint-asian-tractor-20l", name: "Asian Paints Tractor Emulsion 20L", slug: "asian-paints-tractor-emulsion-20l", sku: "PNT-AP-TRC20",
    description: "Asian Paints Tractor Emulsion 20L. Value interior emulsion.",
    shortDescription: "Value interior emulsion 20L",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Interior Paint", subCategorySlug: "interior",
    unit: "Can (20 L)", unitCode: "CAN", unitSymbol: null,
    price: 1800, mrp: 2200, discount: 18, bulkPrice: 1700, bulkMinQty: 5, bulkLabel: "₹1700 at 5+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 5200,
    inStock: true, stockLevel: 800, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.6, isVerified: true },
    images: ["/products/painting/Asian Paints Tractor Emulsion, Base White 20 L.png"],
    specifications: { "Type": "Interior Emulsion", "Size": "20 L", "Finish": "Matt" },
    features: ["Value for money", "Good coverage", "Low VOC"],
    tags: ["paint", "interior", "asian-paints", "tractor"],
  },
  {
    id: "paint-asian-tractor-10l", name: "Asian Paints Tractor Emulsion 10L", slug: "asian-paints-tractor-emulsion-10l", sku: "PNT-AP-TRC10",
    description: "Asian Paints Tractor Emulsion 10L. Value interior emulsion.",
    shortDescription: "Value interior emulsion 10L",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Interior Paint", subCategorySlug: "interior",
    unit: "Can (10 L)", unitCode: "CAN", unitSymbol: null,
    price: 950, mrp: 1150, discount: 17, bulkPrice: 900, bulkMinQty: 10, bulkLabel: "₹900 at 10+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 3800,
    inStock: true, stockLevel: 1000, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.6, isVerified: true },
    images: ["/products/painting/Asian Paints Tractor Emulsion, Base White 10 L.png"],
    specifications: { "Type": "Interior Emulsion", "Size": "10 L", "Finish": "Matt" },
    features: ["Value for money", "Good coverage", "Easy application"],
    tags: ["paint", "interior", "asian-paints", "tractor"],
  },
  {
    id: "paint-asian-tractor-1l", name: "Asian Paints Tractor Emulsion 1L", slug: "asian-paints-tractor-emulsion-1l", sku: "PNT-AP-TRC1",
    description: "Asian Paints Tractor Emulsion 1L. Small pack for touch-ups.",
    shortDescription: "Value interior emulsion 1L",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Interior Paint", subCategorySlug: "interior",
    unit: "Can (1 L)", unitCode: "CAN", unitSymbol: null,
    price: 120, mrp: 145, discount: 17, bulkPrice: 110, bulkMinQty: 20, bulkLabel: "₹110 at 20+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 2100,
    inStock: true, stockLevel: 2000, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Asian Paints Dealer", rating: 4.5, isVerified: true },
    images: ["/products/painting/Asian Paints Tractor Emulsion, Base White 1 L.png"],
    specifications: { "Type": "Interior Emulsion", "Size": "1 L", "Finish": "Matt" },
    features: ["Small pack", "Easy to use", "Good coverage"],
    tags: ["paint", "interior", "asian-paints", "tractor"],
  },
  {
    id: "paint-asian-ace", name: "Asian Paints Ace, Base White", slug: "asian-paints-ace-base-white", sku: "PNT-AP-ACE",
    description: "Asian Paints Ace exterior emulsion for budget exterior painting.",
    shortDescription: "Budget exterior emulsion",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Exterior Paint", subCategorySlug: "exterior",
    unit: "Can (20 L)", unitCode: "CAN", unitSymbol: null,
    price: 1950, mrp: 2400, discount: 19, bulkPrice: 1850, bulkMinQty: 5, bulkLabel: "₹1850 at 5+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 2800,
    inStock: true, stockLevel: 600, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.6, isVerified: true },
    images: ["/products/painting/Asian Paints Ace, Base White.png"],
    specifications: { "Type": "Exterior Emulsion", "Size": "20 L", "Finish": "Matt" },
    features: ["Budget friendly", "Weather proof", "Good coverage"],
    tags: ["paint", "exterior", "asian-paints", "ace"],
  },
  {
    id: "paint-asian-apex-ultima", name: "Asian Paints Apex Ultima, Base White", slug: "asian-paints-apex-ultima-base-white", sku: "PNT-AP-APXU",
    description: "Asian Paints Apex Ultima premium exterior emulsion.",
    shortDescription: "Premium exterior emulsion",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Exterior Paint", subCategorySlug: "exterior",
    unit: "Can (20 L)", unitCode: "CAN", unitSymbol: null,
    price: 2800, mrp: 3500, discount: 20, bulkPrice: 2650, bulkMinQty: 5, bulkLabel: "₹2650 at 5+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.6, reviewCount: 1900,
    inStock: true, stockLevel: 400, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.7, isVerified: true },
    images: ["/products/painting/Asian Paints Apex Ultima, Base White.png"],
    specifications: { "Type": "Exterior Emulsion", "Size": "20 L", "Finish": "Silk" },
    features: ["Premium exterior", "Anti-chalking", "10 year warranty"],
    tags: ["paint", "exterior", "asian-paints", "apex-ultima"],
  },
  {
    id: "paint-apcolite-glossy", name: "Asian Paints Apcolite Premium Glossy Enamel", slug: "asian-paints-apcolite-glossy-enamel", sku: "PNT-AP-APCG",
    description: "Asian Paints Apcolite Premium Glossy Enamel for wood and metal.",
    shortDescription: "Premium glossy enamel for wood & metal",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Enamel", subCategorySlug: "enamel",
    unit: "Can (1 L)", unitCode: "CAN", unitSymbol: null,
    price: 280, mrp: 340, discount: 18, bulkPrice: 260, bulkMinQty: 10, bulkLabel: "₹260 at 10+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 1600,
    inStock: true, stockLevel: 1500, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Asian Paints Dealer", rating: 4.5, isVerified: true },
    images: ["/products/painting/Asian Paints Apcolite Premium Glossy Enamel.png"],
    specifications: { "Type": "Glossy Enamel", "Size": "1 L", "Finish": "Glossy" },
    features: ["Premium finish", "Wood & metal", "Scratch resistant"],
    tags: ["paint", "enamel", "asian-paints", "glossy"],
  },
  {
    id: "paint-apcolite-satin", name: "Asian Paints Apcolite Premium Satin Enamel", slug: "asian-paints-apcolite-satin-enamel", sku: "PNT-AP-APCS",
    description: "Asian Paints Apcolite Premium Satin Enamel for smooth finish.",
    shortDescription: "Premium satin enamel",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Enamel", subCategorySlug: "enamel",
    unit: "Can (1 L)", unitCode: "CAN", unitSymbol: null,
    price: 260, mrp: 320, discount: 19, bulkPrice: 240, bulkMinQty: 10, bulkLabel: "₹240 at 10+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 1400,
    inStock: true, stockLevel: 1500, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Asian Paints Dealer", rating: 4.5, isVerified: true },
    images: ["/products/painting/Asian Paints Apcolite Premium Satin Enamel.png"],
    specifications: { "Type": "Satin Enamel", "Size": "1 L", "Finish": "Satin" },
    features: ["Smooth finish", "Wood & metal", "Non-yellowing"],
    tags: ["paint", "enamel", "asian-paints", "satin"],
  },
  {
    id: "paint-birla-putty", name: "Birla Wall Putty 1kg", slug: "birla-wall-putty-1kg", sku: "PNT-BIR-PT1",
    description: "Birla Wall Putty 1kg for smooth wall preparation.",
    shortDescription: "Wall putty for smooth finish",
    brand: "Birla White", brandSlug: "birla-white", category: "Painting", categorySlug: "painting",
    subCategory: "Putty", subCategorySlug: "putty",
    unit: "Pack (1 kg)", unitCode: "PACK", unitSymbol: null,
    price: 180, mrp: 210, discount: 14, bulkPrice: 165, bulkMinQty: 20, bulkLabel: "₹165 at 20+ packs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 3400,
    inStock: true, stockLevel: 3000, moq: 5, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Birla White Dealer", rating: 4.5, isVerified: true },
    images: ["/products/painting/Birla Putty.png"],
    specifications: { "Type": "Wall Putty", "Size": "1 kg" },
    features: ["Smooth finish", "Good adhesion", "White cement based"],
    tags: ["putty", "birla-white", "wall-preparation"],
  },
  {
    id: "paint-asian-putty", name: "Asian Paints TruCare Acrylic Wall Putty", slug: "asian-paints-trucare-acrylic-wall-putty", sku: "PNT-AP-PTTY",
    description: "Asian Paints TruCare Acrylic Wall Putty for superior wall finish.",
    shortDescription: "Acrylic wall putty for superior finish",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Putty", subCategorySlug: "putty",
    unit: "Pack (20 kg)", unitCode: "PACK", unitSymbol: null,
    price: 350, mrp: 420, discount: 17, bulkPrice: 330, bulkMinQty: 10, bulkLabel: "₹330 at 10+ packs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 1800,
    inStock: true, stockLevel: 2000, moq: 2, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.6, isVerified: true },
    images: ["/products/painting/Asian Paints TruCare Acrylic Wall Putty.png"],
    specifications: { "Type": "Acrylic Putty", "Size": "20 kg" },
    features: ["Acrylic formula", "Smooth finish", "Crack filling"],
    tags: ["putty", "asian-paints", "trucare", "acrylic"],
  },
  {
    id: "paint-asian-wall-putty", name: "Asian Wall Putty", slug: "asian-wall-putty", sku: "PNT-AP-WPT",
    description: "Asian Wall Putty for basic wall preparation.",
    shortDescription: "Basic wall putty",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Putty", subCategorySlug: "putty",
    unit: "Pack (20 kg)", unitCode: "PACK", unitSymbol: null,
    price: 280, mrp: 340, discount: 18, bulkPrice: 260, bulkMinQty: 10, bulkLabel: "₹260 at 10+ packs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.3, reviewCount: 2200,
    inStock: true, stockLevel: 2500, moq: 2, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.4, isVerified: true },
    images: ["/products/painting/Asian Wall putty.png"],
    specifications: { "Type": "Wall Putty", "Size": "20 kg" },
    features: ["Basic putty", "Good adhesion", "White cement based"],
    tags: ["putty", "asian-paints", "wall-putty"],
  },
  {
    id: "paint-birla-white", name: "Birla White", slug: "birla-white", sku: "PNT-BIR-WHT",
    description: "Birla White for white wash and wall care.",
    shortDescription: "White wash and wall care",
    brand: "Birla White", brandSlug: "birla-white", category: "Painting", categorySlug: "painting",
    subCategory: "Putty", subCategorySlug: "putty",
    unit: "Pack (20 kg)", unitCode: "PACK", unitSymbol: null,
    price: 320, mrp: 380, discount: 16, bulkPrice: 300, bulkMinQty: 10, bulkLabel: "₹300 at 10+ packs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 2800,
    inStock: true, stockLevel: 2000, moq: 2, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Birla White Dealer", rating: 4.5, isVerified: true },
    images: ["/products/painting/Birla White.png"],
    specifications: { "Type": "White Cement", "Size": "20 kg" },
    features: ["Pure white", "Good coverage", "Wall care"],
    tags: ["putty", "birla-white", "white-cement"],
  },
  {
    id: "paint-asian-smartcare-damp", name: "Asian Paints SmartCare Damp Proof Advanced", slug: "asian-paints-smartcare-damp-proof", sku: "PNT-AP-SCDP",
    description: "Asian Paints SmartCare Damp Proof Advanced for waterproofing.",
    shortDescription: "Advanced damp proof solution",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Primer", subCategorySlug: "primer",
    unit: "Can (20 L)", unitCode: "CAN", unitSymbol: null,
    price: 1200, mrp: 1500, discount: 20, bulkPrice: 1100, bulkMinQty: 5, bulkLabel: "₹1100 at 5+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 1200,
    inStock: true, stockLevel: 800, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.5, isVerified: true },
    images: ["/products/painting/Asian Paints SmartCare Damp Proof Advanced.png"],
    specifications: { "Type": "Damp Proof", "Size": "20 L" },
    features: ["Waterproofing", "Anti-damp", "Interior use"],
    tags: ["primer", "asian-paints", "smartcare", "damp-proof"],
  },
  {
    id: "paint-asian-smartcare-terracota", name: "Asian Paints SmartCare Damp Proof Terracota 20L", slug: "asian-paints-smartcare-terracota", sku: "PNT-AP-SCDT",
    description: "Asian Paints SmartCare Damp Proof Terracota for exterior waterproofing.",
    shortDescription: "Terracota damp proof for exterior",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Primer", subCategorySlug: "primer",
    unit: "Can (20 L)", unitCode: "CAN", unitSymbol: null,
    price: 1100, mrp: 1400, discount: 21, bulkPrice: 1000, bulkMinQty: 5, bulkLabel: "₹1000 at 5+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 900,
    inStock: true, stockLevel: 600, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.5, isVerified: true },
    images: ["/products/painting/Asian Paints Smartcare Damp Proof Teracota,20 Litre.png"],
    specifications: { "Type": "Damp Proof", "Size": "20 L", "Color": "Terracota" },
    features: ["Exterior waterproofing", "Terracota finish", "Anti-fungal"],
    tags: ["primer", "asian-paints", "smartcare", "terracota"],
  },
  {
    id: "paint-asian-smartcare-ext-primer", name: "Asian Paints SmartCare Damp Sheath Exterior Primer 20L", slug: "asian-paints-smartcare-ext-primer", sku: "PNT-AP-SCEP",
    description: "Asian Paints SmartCare Damp Sheath Exterior Advanced Waterproofing Primer 20L.",
    shortDescription: "Exterior waterproofing primer",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Primer", subCategorySlug: "primer",
    unit: "Can (20 L)", unitCode: "CAN", unitSymbol: null,
    price: 1300, mrp: 1600, discount: 19, bulkPrice: 1200, bulkMinQty: 5, bulkLabel: "₹1200 at 5+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 800,
    inStock: true, stockLevel: 500, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.5, isVerified: true },
    images: ["/products/painting/Asian Paints SmartCare Damp Sheath Exterior Advanced Waterproofing Primer, 20L.png"],
    specifications: { "Type": "Primer", "Size": "20 L", "Use": "Exterior" },
    features: ["Waterproofing primer", "Exterior use", "Advanced formula"],
    tags: ["primer", "asian-paints", "smartcare", "exterior"],
  },
  {
    id: "paint-asian-smartcare-int-primer", name: "Asian Paints SmartCare Damp Sheath Interior Primer 20L", slug: "asian-paints-smartcare-int-primer", sku: "PNT-AP-SCIP",
    description: "Asian Paints SmartCare Damp Sheath Interior Advanced Waterproofing Primer 20L.",
    shortDescription: "Interior waterproofing primer",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Primer", subCategorySlug: "primer",
    unit: "Can (20 L)", unitCode: "CAN", unitSymbol: null,
    price: 1250, mrp: 1550, discount: 19, bulkPrice: 1150, bulkMinQty: 5, bulkLabel: "₹1150 at 5+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 750,
    inStock: true, stockLevel: 500, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.5, isVerified: true },
    images: ["/products/painting/Asian Paints SmartCare Damp Sheath Interior Advanced Waterproofing Primer, 20L.png"],
    specifications: { "Type": "Primer", "Size": "20 L", "Use": "Interior" },
    features: ["Waterproofing primer", "Interior use", "Advanced formula"],
    tags: ["primer", "asian-paints", "smartcare", "interior"],
  },
  {
    id: "paint-asian-ext-primer", name: "Asian Paints TruCare Exterior Wall Primer 20L", slug: "asian-paints-trucare-ext-primer", sku: "PNT-AP-TCXP",
    description: "Asian Paints TruCare Exterior Wall Primer, Water Thinnable, 20 Litre Bucket.",
    shortDescription: "Exterior wall primer 20L",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Primer", subCategorySlug: "primer",
    unit: "Can (20 L)", unitCode: "CAN", unitSymbol: null,
    price: 650, mrp: 800, discount: 19, bulkPrice: 600, bulkMinQty: 10, bulkLabel: "₹600 at 10+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.3, reviewCount: 1100,
    inStock: true, stockLevel: 1000, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.4, isVerified: true },
    images: ["/products/painting/Asian Paints TruCare Exterior Wall Primer, Water Thinnable, 20 Litre Bucket.png"],
    specifications: { "Type": "Exterior Primer", "Size": "20 L" },
    features: ["Water thinnable", "Exterior use", "Good adhesion"],
    tags: ["primer", "asian-paints", "trucare", "exterior"],
  },
  {
    id: "paint-asian-int-primer", name: "Asian Paints TruCare Interior Wall Primer 20L", slug: "asian-paints-trucare-int-primer", sku: "PNT-AP-TCIP",
    description: "Asian Paints TruCare Interior Wall Primer, Water Thinnable, 20 Litre Bucket.",
    shortDescription: "Interior wall primer 20L",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Primer", subCategorySlug: "primer",
    unit: "Can (20 L)", unitCode: "CAN", unitSymbol: null,
    price: 600, mrp: 750, discount: 20, bulkPrice: 550, bulkMinQty: 10, bulkLabel: "₹550 at 10+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.3, reviewCount: 1000,
    inStock: true, stockLevel: 1000, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.4, isVerified: true },
    images: ["/products/painting/Asian Paints TruCare Interior Wall Primer, Water Thinnable, 20 Litre Bucket.png"],
    specifications: { "Type": "Interior Primer", "Size": "20 L" },
    features: ["Water thinnable", "Interior use", "Smooth finish"],
    tags: ["primer", "asian-paints", "trucare", "interior"],
  },
  {
    id: "paint-asian-wood-primer", name: "Asian Paints TruCare White Wood Primer", slug: "asian-paints-trucare-wood-primer", sku: "PNT-AP-TCWP",
    description: "Asian Paints TruCare White Wood Primer for wood surfaces.",
    shortDescription: "White wood primer",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Primer", subCategorySlug: "primer",
    unit: "Can (1 L)", unitCode: "CAN", unitSymbol: null,
    price: 180, mrp: 220, discount: 18, bulkPrice: 165, bulkMinQty: 20, bulkLabel: "₹165 at 20+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 900,
    inStock: true, stockLevel: 2000, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Asian Paints Dealer", rating: 4.4, isVerified: true },
    images: ["/products/painting/Asian Paints TruCare White Wood Primer.png"],
    specifications: { "Type": "Wood Primer", "Size": "1 L", "Color": "White" },
    features: ["Wood surfaces", "Good adhesion", "Stain blocking"],
    tags: ["primer", "asian-paints", "trucare", "wood"],
  },
  {
    id: "paint-asian-metal-primer", name: "Asian Paints TruCare Yellow Metal Primer", slug: "asian-paints-trucare-metal-primer", sku: "PNT-AP-TCMP",
    description: "Asian Paints TruCare Yellow Metal Primer for metal surfaces.",
    shortDescription: "Yellow metal primer",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Primer", subCategorySlug: "primer",
    unit: "Can (1 L)", unitCode: "CAN", unitSymbol: null,
    price: 190, mrp: 230, discount: 17, bulkPrice: 175, bulkMinQty: 20, bulkLabel: "₹175 at 20+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.3, reviewCount: 800,
    inStock: true, stockLevel: 2000, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Asian Paints Dealer", rating: 4.4, isVerified: true },
    images: ["/products/painting/Asian Paints TruCare Yellow Metal Primer.png"],
    specifications: { "Type": "Metal Primer", "Size": "1 L", "Color": "Yellow" },
    features: ["Metal surfaces", "Anti-rust", "Good adhesion"],
    tags: ["primer", "asian-paints", "trucare", "metal"],
  },
  {
    id: "paint-asian-emulsion-base", name: "Asian Paints Premium Emulsion Base White", slug: "asian-paints-premium-emulsion-base-white", sku: "PNT-AP-PEM",
    description: "Asian Paints Premium Emulsion for premium interior walls.",
    shortDescription: "Premium interior emulsion",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Interior Paint", subCategorySlug: "interior",
    unit: "Can (20 L)", unitCode: "CAN", unitSymbol: null,
    price: 2600, mrp: 3200, discount: 19, bulkPrice: 2450, bulkMinQty: 5, bulkLabel: "₹2450 at 5+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.6, reviewCount: 2500,
    inStock: true, stockLevel: 400, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.6, isVerified: true },
    images: ["/products/painting/Asian_Paints_Premium_Emulsion_Paints_Base_White.png"],
    specifications: { "Type": "Interior Emulsion", "Size": "20 L", "Finish": "Silk" },
    features: ["Premium finish", "Washable", "Low odour"],
    tags: ["paint", "interior", "asian-paints", "premium"],
  },
  {
    id: "paint-asian-putty-mixer", name: "Asian Paints TruCare Putty Mixer M02", slug: "asian-paints-trucare-putty-mixer", sku: "PNT-AP-MIX",
    description: "Asian Paints TruCare Economy Multipurpose Putty Mixer M02.",
    shortDescription: "Putty mixer tool",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Accessories", subCategorySlug: "accessories",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 450, mrp: 550, discount: 18, bulkPrice: 420, bulkMinQty: 5, bulkLabel: "₹420 at 5+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.2, reviewCount: 600,
    inStock: true, stockLevel: 500, moq: 1, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Asian Paints Dealer", rating: 4.3, isVerified: true },
    images: ["/products/painting/Asian Paints TruCare Economy Multipurpose Putty Mixer M02.png"],
    specifications: { "Type": "Putty Mixer", "Model": "M02" },
    features: ["Economy mixer", "Multipurpose", "Durable"],
    tags: ["accessories", "asian-paints", "trucare", "mixer"],
  },
  {
    id: "paint-asian-roller", name: "Asian Paints TruCare Roller", slug: "asian-paints-trucare-roller", sku: "PNT-AP-ROL",
    description: "Asian Paints TruCare Roller for smooth paint application.",
    shortDescription: "Paint roller for smooth finish",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Accessories", subCategorySlug: "accessories",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 120, mrp: 150, discount: 20, bulkPrice: 110, bulkMinQty: 10, bulkLabel: "₹110 at 10+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.3, reviewCount: 1200,
    inStock: true, stockLevel: 3000, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Asian Paints Dealer", rating: 4.4, isVerified: true },
    images: ["/products/painting/Asian Paints TruCare Roller.png"],
    specifications: { "Type": "Paint Roller", "Size": "9 inch" },
    features: ["Smooth finish", "Easy to use", "Reusable"],
    tags: ["accessories", "asian-paints", "trucare", "roller"],
  },
  {
    id: "paint-asian-brush", name: "Asian Brush", slug: "asian-brush", sku: "PNT-AP-BRS",
    description: "Asian Brush for paint application.",
    shortDescription: "Paint brush",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Accessories", subCategorySlug: "accessories",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 80, mrp: 100, discount: 20, bulkPrice: 70, bulkMinQty: 20, bulkLabel: "₹70 at 20+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.2, reviewCount: 1500,
    inStock: true, stockLevel: 5000, moq: 5, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Asian Paints Dealer", rating: 4.3, isVerified: true },
    images: ["/products/painting/Asian Brush.png"],
    specifications: { "Type": "Paint Brush", "Size": "3 inch" },
    features: ["Synthetic bristles", "Smooth application", "Durable"],
    tags: ["accessories", "asian-paints", "brush"],
  },
  {
    id: "paint-asian-masking-tape", name: "Asian Masking Tape", slug: "asian-masking-tape", sku: "PNT-AP-TPE",
    description: "Asian Masking Tape for clean paint edges.",
    shortDescription: "Masking tape for clean edges",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Accessories", subCategorySlug: "accessories",
    unit: "Roll", unitCode: "ROLL", unitSymbol: null,
    price: 60, mrp: 75, discount: 20, bulkPrice: 50, bulkMinQty: 50, bulkLabel: "₹50 at 50+ rolls",
    gstRate: 18, gstCode: "GST 18%", rating: 4.3, reviewCount: 900,
    inStock: true, stockLevel: 5000, moq: 10, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Asian Paints Dealer", rating: 4.3, isVerified: true },
    images: ["/products/painting/Asian Masking Tape.png"],
    specifications: { "Type": "Masking Tape", "Width": "1 inch", "Length": "50 m" },
    features: ["Clean edges", "Easy removal", "Residue free"],
    tags: ["accessories", "asian-paints", "masking-tape"],
  },
  {
    id: "paint-asian-putty-blade", name: "Putty Blade", slug: "putty-blade", sku: "PNT-AP-BLD",
    description: "Putty Blade for smooth putty application.",
    shortDescription: "Putty application blade",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Accessories", subCategorySlug: "accessories",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 90, mrp: 110, discount: 18, bulkPrice: 80, bulkMinQty: 20, bulkLabel: "₹80 at 20+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.2, reviewCount: 700,
    inStock: true, stockLevel: 3000, moq: 5, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Asian Paints Dealer", rating: 4.3, isVerified: true },
    images: ["/products/painting/Putty Blade.png"],
    specifications: { "Type": "Putty Blade", "Size": "12 inch" },
    features: ["Steel blade", "Ergonomic handle", "Smooth finish"],
    tags: ["accessories", "putty-blade"],
  },
  {
    id: "paint-asian-sanding-paper", name: "Asian Paints TruStar Sanding Paper", slug: "asian-paints-trustar-sanding-paper", sku: "PNT-AP-SND",
    description: "Asian Paints TruStar Sanding Paper for surface preparation.",
    shortDescription: "Sanding paper for surface prep",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Accessories", subCategorySlug: "accessories",
    unit: "Pack", unitCode: "PACK", unitSymbol: null,
    price: 40, mrp: 50, discount: 20, bulkPrice: 35, bulkMinQty: 50, bulkLabel: "₹35 at 50+ packs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.1, reviewCount: 500,
    inStock: true, stockLevel: 5000, moq: 10, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Asian Paints Dealer", rating: 4.2, isVerified: true },
    images: ["/products/painting/Asian Paints TruStar Sanding Paper.png"],
    specifications: { "Type": "Sanding Paper", "Grit": "180" },
    features: ["Fine grit", "Smooth finish", "Durable"],
    tags: ["accessories", "asian-paints", "sanding-paper"],
  },
  {
    id: "paint-asian-thinner", name: "Asian Paints WOODTECH Thinner", slug: "asian-paints-woodtech-thinner", sku: "PNT-AP-THR",
    description: "Asian Paints WOODTECH General Purpose Thinner (Turpentine Oil).",
    shortDescription: "General purpose thinner",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Accessories", subCategorySlug: "accessories",
    unit: "Can (1 L)", unitCode: "CAN", unitSymbol: null,
    price: 150, mrp: 180, discount: 17, bulkPrice: 135, bulkMinQty: 20, bulkLabel: "₹135 at 20+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.3, reviewCount: 800,
    inStock: true, stockLevel: 3000, moq: 5, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Asian Paints Dealer", rating: 4.3, isVerified: true },
    images: ["/products/painting/Asian Paints WOODTECH General Purpose Thinner (Turpentine Oil).png"],
    specifications: { "Type": "Thinner", "Size": "1 L" },
    features: ["General purpose", "Turpentine oil", "Quick drying"],
    tags: ["accessories", "asian-paints", "thinner"],
  },
  {
    id: "paint-alagar-gypsum", name: "Alagar Super Plast Gypsum Plaster 25kg", slug: "alagar-super-plast-gypsum-25kg", sku: "PNT-ALG-GYP",
    description: "Alagar Super Plast Gypsum Plaster 25kg Bag for smooth wall finishing.",
    shortDescription: "Gypsum plaster 25kg",
    brand: "Alagar", brandSlug: "alagar", category: "Painting", categorySlug: "painting",
    subCategory: "Putty", subCategorySlug: "putty",
    unit: "Bag (25 kg)", unitCode: "BAG", unitSymbol: null,
    price: 450, mrp: 550, discount: 18, bulkPrice: 420, bulkMinQty: 10, bulkLabel: "₹420 at 10+ bags",
    gstRate: 18, gstCode: "GST 18%", rating: 4.3, reviewCount: 400,
    inStock: true, stockLevel: 1000, moq: 2, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Alagar Building Materials", rating: 4.3, isVerified: true },
    images: ["/products/painting/Alagar Super Plast Gypsum Plaster, 25 Kg Bag.png"],
    specifications: { "Type": "Gypsum Plaster", "Weight": "25 kg" },
    features: ["Smooth finish", "Easy application", "Quick setting"],
    tags: ["plaster", "gypsum", "alagar"],
  },
  {
    id: "paint-birla-ext-primer", name: "Birla White Activcoat Exterior Primer 20L", slug: "birla-white-activcoat-ext-primer", sku: "PNT-BIR-ACEP",
    description: "Birla White Activcoat Exterior Primer, 20 Litre Bucket.",
    shortDescription: "Exterior primer 20L",
    brand: "Birla White", brandSlug: "birla-white", category: "Painting", categorySlug: "painting",
    subCategory: "Primer", subCategorySlug: "primer",
    unit: "Can (20 L)", unitCode: "CAN", unitSymbol: null,
    price: 700, mrp: 850, discount: 18, bulkPrice: 650, bulkMinQty: 5, bulkLabel: "₹650 at 5+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 600,
    inStock: true, stockLevel: 500, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Birla White Dealer", rating: 4.4, isVerified: true },
    images: ["/products/painting/Birla White Activcoat Exterior Primer, 20 Litre Bucket.png"],
    specifications: { "Type": "Exterior Primer", "Size": "20 L" },
    features: ["Exterior use", "Good adhesion", "Weather resistant"],
    tags: ["primer", "birla-white", "exterior"],
  },
  {
    id: "paint-birla-int-primer", name: "Birla White Activcoat Interior Primer 20L", slug: "birla-white-activcoat-int-primer", sku: "PNT-BIR-ACIP",
    description: "Birla White Activcoat Interior Primer, 20 Litre Bucket.",
    shortDescription: "Interior primer 20L",
    brand: "Birla White", brandSlug: "birla-white", category: "Painting", categorySlug: "painting",
    subCategory: "Primer", subCategorySlug: "primer",
    unit: "Can (20 L)", unitCode: "CAN", unitSymbol: null,
    price: 650, mrp: 800, discount: 19, bulkPrice: 600, bulkMinQty: 5, bulkLabel: "₹600 at 5+ cans",
    gstRate: 18, gstCode: "GST 18%", rating: 4.3, reviewCount: 550,
    inStock: true, stockLevel: 500, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Birla White Dealer", rating: 4.4, isVerified: true },
    images: ["/products/painting/Birla White Activcoat Interior Primer, 20 Litre Bucket.png"],
    specifications: { "Type": "Interior Primer", "Size": "20 L" },
    features: ["Interior use", "Smooth finish", "Good adhesion"],
    tags: ["primer", "birla-white", "interior"],
  },
  {
    id: "paint-interior-putty", name: "TruCare Acrylic Wall Putty Interior", slug: "trucare-acrylic-wall-putty-interior", sku: "PNT-TC-IPT",
    description: "Interior walls undercoats TruCare acrylic wall putty by Asian Paints.",
    shortDescription: "Interior acrylic wall putty",
    brand: "Asian Paints", brandSlug: "asian-paints", category: "Painting", categorySlug: "painting",
    subCategory: "Putty", subCategorySlug: "putty",
    unit: "Pack (20 kg)", unitCode: "PACK", unitSymbol: null,
    price: 340, mrp: 410, discount: 17, bulkPrice: 320, bulkMinQty: 10, bulkLabel: "₹320 at 10+ packs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 1100,
    inStock: true, stockLevel: 2000, moq: 2, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Asian Paints Dealer", rating: 4.5, isVerified: true },
    images: ["/products/painting/interior-walls-undercoats-trucare-acrylic-wall-putty-asian-paints.png"],
    specifications: { "Type": "Acrylic Putty", "Size": "20 kg" },
    features: ["Interior use", "Acrylic formula", "Smooth finish"],
    tags: ["putty", "asian-paints", "trucare", "acrylic"],
  },

  // ═══════════════════════════════════════════════════════════════
  // LIGHTING (17 products)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "light-philips-downlight-round", name: "Philips Ultra Glow LED Downlight Round", slug: "philips-ultra-glow-led-downlight-round", sku: "LGT-PH-DLR",
    description: "Philips Ultra Glow LED Downlight, Round for ceiling installation.",
    shortDescription: "LED downlight for ceiling",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "LED Downlight", subCategorySlug: "downlight",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 450, mrp: 599, discount: 25, bulkPrice: 400, bulkMinQty: 10, bulkLabel: "₹400 at 10+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 1800,
    inStock: true, stockLevel: 2000, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Philips Authorized Dealer", rating: 4.6, isVerified: true },
    images: ["/products/lighting/Philips Ultra Glow 3-in-1 LED Downlight, Round.webp"],
    specifications: { "Type": "LED Downlight", "Wattage": "12W", "Color": "Cool Day Light" },
    features: ["Energy efficient", "Long life", "3 year warranty"],
    tags: ["lighting", "led", "philips", "downlight"],
  },
  {
    id: "light-philips-downlight-3in1", name: "Philips Ultra Glow 3-in-1 LED Downlight Round", slug: "philips-ultra-glow-3in1-downlight", sku: "LGT-PH-DL31",
    description: "Philips Ultra Glow 3-in-1 LED Downlight, Round with tunable color.",
    shortDescription: "3-in-1 tunable LED downlight",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "LED Downlight", subCategorySlug: "downlight",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 650, mrp: 899, discount: 28, bulkPrice: 580, bulkMinQty: 10, bulkLabel: "₹580 at 10+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.6, reviewCount: 1200,
    inStock: true, stockLevel: 1500, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Philips Authorized Dealer", rating: 4.6, isVerified: true },
    images: ["/products/lighting/Philips Full Glow LED Surface Light, Round.webp"],
    specifications: { "Type": "LED Downlight", "Wattage": "15W", "Color": "Tunable" },
    features: ["3-in-1 color", "Dimmable", "Long life"],
    tags: ["lighting", "led", "philips", "downlight", "tunable"],
  },
  {
    id: "light-philips-surface-3in1", name: "Philips Full Glow 3-in-1 Surface Light Round", slug: "philips-full-glow-3in1-surface-light", sku: "LGT-PH-SL31",
    description: "Philips Full Glow 3-in-1 Surface Light, Round for surface mount.",
    shortDescription: "3-in-1 surface mounted light",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "LED Downlight", subCategorySlug: "downlight",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 750, mrp: 999, discount: 25, bulkPrice: 680, bulkMinQty: 10, bulkLabel: "₹680 at 10+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 900,
    inStock: true, stockLevel: 1000, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Philips Authorized Dealer", rating: 4.5, isVerified: true },
    images: ["/products/lighting/Philip Ultra Glow LED Downlight, Round.webp"],
    specifications: { "Type": "Surface Light", "Wattage": "18W", "Color": "Tunable" },
    features: ["Surface mount", "3-in-1 color", "Bright illumination"],
    tags: ["lighting", "led", "philips", "surface"],
  },
  {
    id: "light-philips-downlight-fullglow", name: "Philips Full Glow LED Surface Light Round", slug: "philips-full-glow-led-surface-light", sku: "LGT-PH-FGSL",
    description: "Philips Full Glow LED Surface Light, Round for bright illumination.",
    shortDescription: "Full glow LED surface light",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "LED Downlight", subCategorySlug: "downlight",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 550, mrp: 749, discount: 27, bulkPrice: 490, bulkMinQty: 10, bulkLabel: "₹490 at 10+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 1100,
    inStock: true, stockLevel: 1500, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Philips Authorized Dealer", rating: 4.5, isVerified: true },
    images: ["/products/lighting/Philips AstraSpot Next LED COB light.webp"],
    specifications: { "Type": "Surface Light", "Wattage": "15W", "Color": "Cool Day Light" },
    features: ["Full glow", "Surface mount", "Energy efficient"],
    tags: ["lighting", "led", "philips", "surface"],
  },
  {
    id: "light-philips-strip-5m", name: "Philips EvenGlow LED Strip Light 5m", slug: "philips-evenglow-led-strip-5m", sku: "LGT-PH-STR5",
    description: "Philips EvenGlow LED Strip Light, 5m for decorative lighting.",
    shortDescription: "5m LED strip light",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "Strip Light", subCategorySlug: "strip",
    unit: "Roll", unitCode: "ROLL", unitSymbol: null,
    price: 1200, mrp: 1599, discount: 25, bulkPrice: 1080, bulkMinQty: 5, bulkLabel: "₹1080 at 5+ rolls",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 800,
    inStock: true, stockLevel: 800, moq: 1, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Philips Authorized Dealer", rating: 4.5, isVerified: true },
    images: ["/products/lighting/Philips EvenGlow LED Strip Light, 5m.webp"],
    specifications: { "Type": "LED Strip", "Length": "5 m", "Wattage": "14W/m" },
    features: ["Flexible strip", "Cuttable", "Adhesive backing"],
    tags: ["lighting", "led", "philips", "strip"],
  },
  {
    id: "light-philips-strip-driver", name: "Philips LED Strip Light Driver", slug: "philips-led-strip-light-driver", sku: "LGT-PH-STRD",
    description: "Philips LED Strip Light Driver for powering strip lights.",
    shortDescription: "LED strip light driver",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "Accessories", subCategorySlug: "accessories",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 350, mrp: 450, discount: 22, bulkPrice: 310, bulkMinQty: 10, bulkLabel: "₹310 at 10+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 600,
    inStock: true, stockLevel: 1000, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Philips Authorized Dealer", rating: 4.4, isVerified: true },
    images: ["/products/lighting/Philips LED Strip Light Driver.webp"],
    specifications: { "Type": "LED Driver", "Output": "12V DC" },
    features: ["Compatible with Philips strips", "Short circuit protection", "Efficient"],
    tags: ["lighting", "accessories", "philips", "driver"],
  },
  {
    id: "light-philips-rope-50m", name: "Philips Marathon Ultra LED Rope Light 50m", slug: "philips-marathon-ultra-led-rope-50m", sku: "LGT-PH-RPE50",
    description: "Philips Marathon Ultra LED Rope Light, 50m Strip Light, Warm White.",
    shortDescription: "50m LED rope light warm white",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "Rope Light", subCategorySlug: "rope",
    unit: "Roll", unitCode: "ROLL", unitSymbol: null,
    price: 2500, mrp: 3200, discount: 22, bulkPrice: 2250, bulkMinQty: 3, bulkLabel: "₹2250 at 3+ rolls",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 500,
    inStock: true, stockLevel: 300, moq: 1, deliveryDays: 2, freeDelivery: true,
    seller: { name: "Philips Authorized Dealer", rating: 4.5, isVerified: true },
    images: ["/products/lighting/Philips Marathon Ultra LED Rope Light, 50m (Strip Light), Warm White.webp"],
    specifications: { "Type": "LED Rope Light", "Length": "50 m", "Color": "Warm White" },
    features: ["Marathon Ultra", "50m length", "Outdoor rated"],
    tags: ["lighting", "led", "philips", "rope"],
  },
  {
    id: "light-philips-tube-20w", name: "Philips Slimline Ultra LED Tube Light 20W", slug: "philips-slimline-ultra-led-tube-20w", sku: "LGT-PH-TB20",
    description: "Philips Slimline Ultra LED Tube Light, 20W for bright tube illumination.",
    shortDescription: "20W slim LED tube light",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "Tube Light", subCategorySlug: "tube",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 350, mrp: 499, discount: 30, bulkPrice: 310, bulkMinQty: 10, bulkLabel: "₹310 at 10+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 1500,
    inStock: true, stockLevel: 2000, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Philips Authorized Dealer", rating: 4.6, isVerified: true },
    images: ["/products/lighting/Philips Slimline Ultra LED Tube Light, 20W.webp"],
    specifications: { "Type": "LED Tube", "Wattage": "20W", "Length": "4 ft" },
    features: ["Slim design", "Energy saving", "Instant start"],
    tags: ["lighting", "led", "philips", "tube"],
  },
  {
    id: "light-philips-cob-astraspot", name: "Philips AstraSpot Next LED COB Light", slug: "philips-astraspot-next-led-cob-light", sku: "LGT-PH-COB1",
    description: "Philips AstraSpot Next LED COB light for focused illumination.",
    shortDescription: "COB spotlight for focused light",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "COB Light", subCategorySlug: "cob",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 800, mrp: 1099, discount: 27, bulkPrice: 720, bulkMinQty: 10, bulkLabel: "₹720 at 10+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.6, reviewCount: 700,
    inStock: true, stockLevel: 800, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Philips Authorized Dealer", rating: 4.6, isVerified: true },
    images: ["/products/lighting/Philips Astraspot 3-In-1 COB Light, Tunable, White.webp"],
    specifications: { "Type": "COB Light", "Wattage": "12W", "Color": "Tunable" },
    features: ["COB technology", "Focused beam", "3-in-1 tunable"],
    tags: ["lighting", "led", "philips", "cob"],
  },
  {
    id: "light-philips-cob-3in1", name: "Philips AstraSpot 3-In-1 COB Light Tunable", slug: "philips-astraspot-3in1-cob-light", sku: "LGT-PH-COB3",
    description: "Philips AstraSpot 3-In-1 COB Light, Tunable, White for adjustable lighting.",
    shortDescription: "3-in-1 tunable COB light",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "COB Light", subCategorySlug: "cob",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 950, mrp: 1299, discount: 27, bulkPrice: 850, bulkMinQty: 10, bulkLabel: "₹850 at 10+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.6, reviewCount: 600,
    inStock: true, stockLevel: 600, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Philips Authorized Dealer", rating: 4.6, isVerified: true },
    images: ["/products/lighting/Philips AstraSpot Next LED COB light.webp"],
    specifications: { "Type": "COB Light", "Wattage": "15W", "Color": "Tunable" },
    features: ["3-in-1 tunable", "COB technology", "Adjustable"],
    tags: ["lighting", "led", "philips", "cob", "tunable"],
  },
  {
    id: "light-crompton-recess", name: "Crompton LED Star Slim Recess Panel Round", slug: "crompton-led-star-slim-recess-panel", sku: "LGT-CR-RP6",
    description: "Crompton LED Star Slim Recess Panel Round 6 inch for ceiling recess.",
    shortDescription: "Slim recess panel for ceiling",
    brand: "Crompton", brandSlug: "crompton", category: "Lighting", categorySlug: "lighting",
    subCategory: "LED Downlight", subCategorySlug: "downlight",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 380, mrp: 500, discount: 24, bulkPrice: 340, bulkMinQty: 10, bulkLabel: "₹340 at 10+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 900,
    inStock: true, stockLevel: 1500, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Crompton Authorized Dealer", rating: 4.5, isVerified: true },
    images: ["/products/lighting/crompton-led-star-slim-recess-panel-round-6k-1678368249930_SKU-0684_0-1756465491712-Photoroom.png"],
    specifications: { "Type": "Recess Panel", "Size": "6 inch", "Wattage": "12W" },
    features: ["Slim design", "Recess mount", "Energy efficient"],
    tags: ["lighting", "led", "crompton", "recess"],
  },
  {
    id: "light-shopping-1", name: "Philips LED Bulb 9W", slug: "philips-led-bulb-9w", sku: "LGT-PH-B9W",
    description: "Philips LED Bulb 9W for general lighting needs.",
    shortDescription: "9W LED bulb",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "LED Downlight", subCategorySlug: "downlight",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 120, mrp: 160, discount: 25, bulkPrice: 105, bulkMinQty: 20, bulkLabel: "₹105 at 20+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.3, reviewCount: 3000,
    inStock: true, stockLevel: 5000, moq: 5, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Philips Authorized Dealer", rating: 4.5, isVerified: true },
    images: ["/products/lighting/shopping-Photoroom (3).png"],
    specifications: { "Type": "LED Bulb", "Wattage": "9W", "Base": "B22" },
    features: ["Energy efficient", "Long life", "Instant on"],
    tags: ["lighting", "led", "philips", "bulb"],
  },
  {
    id: "light-shopping-2", name: "Philips LED Bulb 12W", slug: "philips-led-bulb-12w", sku: "LGT-PH-B12W",
    description: "Philips LED Bulb 12W for brighter illumination.",
    shortDescription: "12W LED bulb",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "LED Downlight", subCategorySlug: "downlight",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 150, mrp: 200, discount: 25, bulkPrice: 130, bulkMinQty: 20, bulkLabel: "₹130 at 20+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.3, reviewCount: 2500,
    inStock: true, stockLevel: 5000, moq: 5, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Philips Authorized Dealer", rating: 4.5, isVerified: true },
    images: ["/products/lighting/shopping-Photoroom (4).png"],
    specifications: { "Type": "LED Bulb", "Wattage": "12W", "Base": "B22" },
    features: ["Bright illumination", "Energy efficient", "Long life"],
    tags: ["lighting", "led", "philips", "bulb"],
  },
  {
    id: "light-shopping-3", name: "Philips LED Bulb 15W", slug: "philips-led-bulb-15w", sku: "LGT-PH-B15W",
    description: "Philips LED Bulb 15W for maximum brightness.",
    shortDescription: "15W LED bulb",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "LED Downlight", subCategorySlug: "downlight",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 180, mrp: 240, discount: 25, bulkPrice: 160, bulkMinQty: 20, bulkLabel: "₹160 at 20+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 2000,
    inStock: true, stockLevel: 5000, moq: 5, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Philips Authorized Dealer", rating: 4.5, isVerified: true },
    images: ["/products/lighting/shopping-Photoroom (5).png"],
    specifications: { "Type": "LED Bulb", "Wattage": "15W", "Base": "B22" },
    features: ["Maximum brightness", "Energy efficient", "Long life"],
    tags: ["lighting", "led", "philips", "bulb"],
  },
  {
    id: "light-philips-3head", name: "Philips 3-Head LED Spotlight", slug: "philips-3head-led-spotlight", sku: "LGT-PH-3HD",
    description: "Philips 3-Head LED Spotlight for adjustable lighting.",
    shortDescription: "3-head adjustable spotlight",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "COB Light", subCategorySlug: "cob",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 1100, mrp: 1499, discount: 27, bulkPrice: 980, bulkMinQty: 5, bulkLabel: "₹980 at 5+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 400,
    inStock: true, stockLevel: 500, moq: 1, deliveryDays: 2, freeDelivery: false,
    seller: { name: "Philips Authorized Dealer", rating: 4.5, isVerified: true },
    images: ["/products/lighting/3_79422223-038b-4f9f-8556-b11b186110c1-Photoroom.png"],
    specifications: { "Type": "3-Head Spotlight", "Wattage": "20W", "Color": "Cool Day Light" },
    features: ["3 adjustable heads", "Focused beam", "Modern design"],
    tags: ["lighting", "led", "philips", "spotlight"],
  },
  {
    id: "light-philips-plug", name: "Philips LED Plug Light", slug: "philips-led-plug-light", sku: "LGT-PH-PLG",
    description: "Philips LED Plug Light for convenient portable lighting.",
    shortDescription: "Portable LED plug light",
    brand: "Philips", brandSlug: "philips", category: "Lighting", categorySlug: "lighting",
    subCategory: "LED Downlight", subCategorySlug: "downlight",
    unit: "Piece", unitCode: "PC", unitSymbol: null,
    price: 250, mrp: 350, discount: 29, bulkPrice: 220, bulkMinQty: 10, bulkLabel: "₹220 at 10+ pcs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.3, reviewCount: 800,
    inStock: true, stockLevel: 1500, moq: 2, deliveryDays: 1, freeDelivery: false,
    seller: { name: "Philips Authorized Dealer", rating: 4.4, isVerified: true },
    images: ["/products/lighting/61Yfy1lpogL._AC_UF894,1000_QL80_-Photoroom.png"],
    specifications: { "Type": "Plug Light", "Wattage": "5W", "Base": "B22" },
    features: ["Portable", "Compact", "Energy efficient"],
    tags: ["lighting", "led", "philips", "plug"],
  },

  // ═══════════════════════════════════════════════════════════════
  // TILING (14 products)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "tile-drfixit", name: "Dr Fixit Waterproofing Solution", slug: "dr-fixit-waterproofing", sku: "TIL-DF-WP",
    description: "Dr Fixit Waterproofing Solution for walls and roofs.",
    shortDescription: "Waterproofing solution",
    brand: "Dr Fixit", brandSlug: "dr-fixit", category: "Tiling", categorySlug: "tiling",
    subCategory: "Waterproofing", subCategorySlug: "waterproofing",
    unit: "Pack (20 kg)", unitCode: "PACK", unitSymbol: null,
    price: 850, mrp: 1100, discount: 23, bulkPrice: 780, bulkMinQty: 5, bulkLabel: "₹780 at 5+ packs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.6, reviewCount: 2200,
    inStock: true, stockLevel: 1000, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Dr Fixit Dealer", rating: 4.6, isVerified: true },
    images: ["/products/tiling/Dr Fixit.png"],
    specifications: { "Type": "Waterproofing", "Weight": "20 kg" },
    features: ["Crack bridging", "Water resistant", "Flexible"],
    tags: ["tiling", "waterproofing", "dr-fixit"],
  },
  {
    id: "tile-kajaria-1", name: "Kajaria Adhesives Tiling", slug: "kajaria-adhesives-tiling", sku: "TIL-KJ-ADH",
    description: "Kajaria Adhesives Tiling for strong tile bonding.",
    shortDescription: "Tile adhesive for strong bonding",
    brand: "Kajaria", brandSlug: "kajaria", category: "Tiling", categorySlug: "tiling",
    subCategory: "Adhesive", subCategorySlug: "adhesive",
    unit: "Bag (20 kg)", unitCode: "BAG", unitSymbol: null,
    price: 420, mrp: 550, discount: 24, bulkPrice: 380, bulkMinQty: 20, bulkLabel: "₹380 at 20+ bags",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 1800,
    inStock: true, stockLevel: 2000, moq: 5, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Kajaria Dealer", rating: 4.5, isVerified: true },
    images: ["/products/tiling/Kajaria Adhesives Tiling.png"],
    specifications: { "Type": "Tile Adhesive", "Weight": "20 kg" },
    features: ["Strong bonding", "Water resistant", "Easy application"],
    tags: ["tiling", "adhesive", "kajaria"],
  },
  {
    id: "tile-kajaria-2", name: "Kajaria Adhesives Tiling Premium", slug: "kajaria-adhesives-tiling-premium", sku: "TIL-KJ-ADP",
    description: "Kajaria Adhesives Tiling Premium for heavy-duty tile installation.",
    shortDescription: "Premium tile adhesive",
    brand: "Kajaria", brandSlug: "kajaria", category: "Tiling", categorySlug: "tiling",
    subCategory: "Adhesive", subCategorySlug: "adhesive",
    unit: "Bag (20 kg)", unitCode: "BAG", unitSymbol: null,
    price: 480, mrp: 620, discount: 23, bulkPrice: 430, bulkMinQty: 20, bulkLabel: "₹430 at 20+ bags",
    gstRate: 18, gstCode: "GST 18%", rating: 4.6, reviewCount: 1200,
    inStock: true, stockLevel: 1500, moq: 5, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Kajaria Dealer", rating: 4.6, isVerified: true },
    images: ["/products/tiling/Kajaria Adhesives Tiling 02.png"],
    specifications: { "Type": "Tile Adhesive", "Weight": "20 kg", "Grade": "Premium" },
    features: ["Heavy duty", "Strong bonding", "Premium quality"],
    tags: ["tiling", "adhesive", "kajaria", "premium"],
  },
  {
    id: "tile-kajaria-3", name: "Kajaria Adhesives Tiling Standard", slug: "kajaria-adhesives-tiling-standard", sku: "TIL-KJ-ADS",
    description: "Kajaria Adhesives Tiling Standard for regular tile installation.",
    shortDescription: "Standard tile adhesive",
    brand: "Kajaria", brandSlug: "kajaria", category: "Tiling", categorySlug: "tiling",
    subCategory: "Adhesive", subCategorySlug: "adhesive",
    unit: "Bag (20 kg)", unitCode: "BAG", unitSymbol: null,
    price: 380, mrp: 500, discount: 24, bulkPrice: 340, bulkMinQty: 20, bulkLabel: "₹340 at 20+ bags",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 1500,
    inStock: true, stockLevel: 2000, moq: 5, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Kajaria Dealer", rating: 4.4, isVerified: true },
    images: ["/products/tiling/Kajaria Adhesives Tiling 03.png"],
    specifications: { "Type": "Tile Adhesive", "Weight": "20 kg", "Grade": "Standard" },
    features: ["Standard grade", "Good bonding", "Economical"],
    tags: ["tiling", "adhesive", "kajaria", "standard"],
  },
  {
    id: "tile-roff-1", name: "Roff Tiling Adhesive", slug: "roff-tiling-adhesive", sku: "TIL-RF-ADH",
    description: "Roff Tiling Adhesive for professional tile installation.",
    shortDescription: "Professional tile adhesive",
    brand: "Roff", brandSlug: "roff", category: "Tiling", categorySlug: "tiling",
    subCategory: "Adhesive", subCategorySlug: "adhesive",
    unit: "Bag (20 kg)", unitCode: "BAG", unitSymbol: null,
    price: 480, mrp: 600, discount: 20, bulkPrice: 430, bulkMinQty: 20, bulkLabel: "₹430 at 20+ bags",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 1500,
    inStock: true, stockLevel: 1500, moq: 5, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Roff Dealer", rating: 4.5, isVerified: true },
    images: ["/products/tiling/Roff T1.png"],
    specifications: { "Type": "Tile Adhesive", "Weight": "20 kg" },
    features: ["Professional grade", "Strong bonding", "Water resistant"],
    tags: ["tiling", "adhesive", "roff"],
  },
  {
    id: "tile-roff-2", name: "Roff Tiling Adhesive Premium", slug: "roff-tiling-adhesive-premium", sku: "TIL-RF-ADP",
    description: "Roff Tiling Adhesive Premium for large format tiles.",
    shortDescription: "Premium adhesive for large tiles",
    brand: "Roff", brandSlug: "roff", category: "Tiling", categorySlug: "tiling",
    subCategory: "Adhesive", subCategorySlug: "adhesive",
    unit: "Bag (20 kg)", unitCode: "BAG", unitSymbol: null,
    price: 550, mrp: 700, discount: 21, bulkPrice: 490, bulkMinQty: 20, bulkLabel: "₹490 at 20+ bags",
    gstRate: 18, gstCode: "GST 18%", rating: 4.6, reviewCount: 900,
    inStock: true, stockLevel: 1000, moq: 5, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Roff Dealer", rating: 4.6, isVerified: true },
    images: ["/products/tiling/Roff T02.png"],
    specifications: { "Type": "Tile Adhesive", "Weight": "20 kg", "Grade": "Premium" },
    features: ["Large format tiles", "Premium quality", "Flexible"],
    tags: ["tiling", "adhesive", "roff", "premium"],
  },
  {
    id: "tile-roff-3", name: "Roff Tiling Adhesive Standard", slug: "roff-tiling-adhesive-standard", sku: "TIL-RF-ADS",
    description: "Roff Tiling Adhesive Standard for regular tile installation.",
    shortDescription: "Standard tile adhesive",
    brand: "Roff", brandSlug: "roff", category: "Tiling", categorySlug: "tiling",
    subCategory: "Adhesive", subCategorySlug: "adhesive",
    unit: "Bag (20 kg)", unitCode: "BAG", unitSymbol: null,
    price: 420, mrp: 550, discount: 24, bulkPrice: 380, bulkMinQty: 20, bulkLabel: "₹380 at 20+ bags",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 1200,
    inStock: true, stockLevel: 1500, moq: 5, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Roff Dealer", rating: 4.4, isVerified: true },
    images: ["/products/tiling/Roff T03.png"],
    specifications: { "Type": "Tile Adhesive", "Weight": "20 kg", "Grade": "Standard" },
    features: ["Standard grade", "Good bonding", "Economical"],
    tags: ["tiling", "adhesive", "roff", "standard"],
  },
  {
    id: "tile-roff-4", name: "Roff Tiling Adhesive Economy", slug: "roff-tiling-adhesive-economy", sku: "TIL-RF-ADE",
    description: "Roff Tiling Adhesive Economy for budget tile installation.",
    shortDescription: "Economy tile adhesive",
    brand: "Roff", brandSlug: "roff", category: "Tiling", categorySlug: "tiling",
    subCategory: "Adhesive", subCategorySlug: "adhesive",
    unit: "Bag (20 kg)", unitCode: "BAG", unitSymbol: null,
    price: 350, mrp: 460, discount: 24, bulkPrice: 310, bulkMinQty: 20, bulkLabel: "₹310 at 20+ bags",
    gstRate: 18, gstCode: "GST 18%", rating: 4.3, reviewCount: 1000,
    inStock: true, stockLevel: 2000, moq: 5, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Roff Dealer", rating: 4.3, isVerified: true },
    images: ["/products/tiling/Roff T04.png"],
    specifications: { "Type": "Tile Adhesive", "Weight": "20 kg", "Grade": "Economy" },
    features: ["Economical", "Basic bonding", "Good value"],
    tags: ["tiling", "adhesive", "roff", "economy"],
  },
  {
    id: "tile-roff-5", name: "Roff Tiling Adhesive Wall", slug: "roff-tiling-adhesive-wall", sku: "TIL-RF-ADW",
    description: "Roff Tiling Adhesive Wall for wall tile installation.",
    shortDescription: "Wall tile adhesive",
    brand: "Roff", brandSlug: "roff", category: "Tiling", categorySlug: "tiling",
    subCategory: "Adhesive", subCategorySlug: "adhesive",
    unit: "Bag (20 kg)", unitCode: "BAG", unitSymbol: null,
    price: 450, mrp: 580, discount: 22, bulkPrice: 400, bulkMinQty: 20, bulkLabel: "₹400 at 20+ bags",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 800,
    inStock: true, stockLevel: 1200, moq: 5, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Roff Dealer", rating: 4.4, isVerified: true },
    images: ["/products/tiling/Roff T05.png"],
    specifications: { "Type": "Wall Adhesive", "Weight": "20 kg" },
    features: ["Wall tiles", "Strong grip", "Non-sag"],
    tags: ["tiling", "adhesive", "roff", "wall"],
  },
  {
    id: "tile-weber", name: "Weber Tiling Solution", slug: "weber-tiling-solution", sku: "TIL-WB-SOL",
    description: "Weber Tiling Solution for reliable tile bonding.",
    shortDescription: "Reliable tiling solution",
    brand: "Weber", brandSlug: "weber", category: "Tiling", categorySlug: "tiling",
    subCategory: "Adhesive", subCategorySlug: "adhesive",
    unit: "Bag (20 kg)", unitCode: "BAG", unitSymbol: null,
    price: 390, mrp: 500, discount: 22, bulkPrice: 350, bulkMinQty: 20, bulkLabel: "₹350 at 20+ bags",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 1200,
    inStock: true, stockLevel: 1500, moq: 5, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Weber Dealer", rating: 4.4, isVerified: true },
    images: ["/products/tiling/Weber.png"],
    specifications: { "Type": "Tile Adhesive", "Weight": "20 kg" },
    features: ["Reliable bonding", "Water resistant", "Easy application"],
    tags: ["tiling", "adhesive", "weber"],
  },
  {
    id: "tile-apex", name: "Apex Endura Waterproofing", slug: "apex-endura-waterproofing", sku: "TIL-AEX-WP",
    description: "Apex Endura Waterproofing for comprehensive water protection.",
    shortDescription: "Comprehensive waterproofing",
    brand: "Apex", brandSlug: "apex", category: "Tiling", categorySlug: "tiling",
    subCategory: "Waterproofing", subCategorySlug: "waterproofing",
    unit: "Pack (20 kg)", unitCode: "PACK", unitSymbol: null,
    price: 720, mrp: 900, discount: 20, bulkPrice: 650, bulkMinQty: 5, bulkLabel: "₹650 at 5+ packs",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 980,
    inStock: true, stockLevel: 800, moq: 1, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Apex Dealer", rating: 4.4, isVerified: true },
    images: ["/products/tiling/Apex Endura.png"],
    specifications: { "Type": "Waterproofing", "Weight": "20 kg" },
    features: ["Endura protection", "Crack resistant", "Flexible"],
    tags: ["tiling", "waterproofing", "apex"],
  },
  {
    id: "tile-bostik", name: "Bostik Tiling Adhesive", slug: "bostik-tiling-adhesive", sku: "TIL-BST-ADH",
    description: "Bostik Tiling Adhesive for professional tile installation.",
    shortDescription: "Professional tiling adhesive",
    brand: "Bostik", brandSlug: "bostik", category: "Tiling", categorySlug: "tiling",
    subCategory: "Adhesive", subCategorySlug: "adhesive",
    unit: "Bag (20 kg)", unitCode: "BAG", unitSymbol: null,
    price: 550, mrp: 700, discount: 21, bulkPrice: 490, bulkMinQty: 20, bulkLabel: "₹490 at 20+ bags",
    gstRate: 18, gstCode: "GST 18%", rating: 4.4, reviewCount: 870,
    inStock: true, stockLevel: 1000, moq: 5, deliveryDays: 1, freeDelivery: true,
    seller: { name: "Bostik Dealer", rating: 4.4, isVerified: true },
    images: ["/products/tiling/Bostik.png"],
    specifications: { "Type": "Tile Adhesive", "Weight": "20 kg" },
    features: ["Professional grade", "Strong bonding", "Flexible"],
    tags: ["tiling", "adhesive", "bostik"],
  },
  {
    id: "tile-kerakoll", name: "Kerakoll Tiling Adhesive", slug: "kerakoll-tiling-adhesive", sku: "TIL-KRK-ADH",
    description: "Kerakoll Tiling Adhesive for premium tile installation.",
    shortDescription: "Premium tiling adhesive",
    brand: "Kerakoll", brandSlug: "kerakoll", category: "Tiling", categorySlug: "tiling",
    subCategory: "Adhesive", subCategorySlug: "adhesive",
    unit: "Bag (20 kg)", unitCode: "BAG", unitSymbol: null,
    price: 600, mrp: 780, discount: 23, bulkPrice: 540, bulkMinQty: 20, bulkLabel: "₹540 at 20+ bags",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 600,
    inStock: true, stockLevel: 800, moq: 5, deliveryDays: 2, freeDelivery: true,
    seller: { name: "Kerakoll Dealer", rating: 4.5, isVerified: true },
    images: ["/products/tiling/Kerakoll Tiling.png"],
    specifications: { "Type": "Tile Adhesive", "Weight": "20 kg", "Grade": "Premium" },
    features: ["Premium quality", "Flexible", "High bond strength"],
    tags: ["tiling", "adhesive", "kerakoll", "premium"],
  },
  {
    id: "tile-myk", name: "MYK Laticrete Tiling Adhesive", slug: "myk-laticrete-tiling-adhesive", sku: "TIL-MYK-ADH",
    description: "MYK Laticrete Tiling Adhesive for advanced tile installation.",
    shortDescription: "Advanced tiling adhesive",
    brand: "MYK Laticrete", brandSlug: "myk-laticrete", category: "Tiling", categorySlug: "tiling",
    subCategory: "Adhesive", subCategorySlug: "adhesive",
    unit: "Bag (20 kg)", unitCode: "BAG", unitSymbol: null,
    price: 650, mrp: 850, discount: 24, bulkPrice: 580, bulkMinQty: 20, bulkLabel: "₹580 at 20+ bags",
    gstRate: 18, gstCode: "GST 18%", rating: 4.5, reviewCount: 500,
    inStock: true, stockLevel: 600, moq: 5, deliveryDays: 2, freeDelivery: true,
    seller: { name: "MYK Laticrete Dealer", rating: 4.5, isVerified: true },
    images: ["/products/tiling/MYK Laticrete.png"],
    specifications: { "Type": "Tile Adhesive", "Weight": "20 kg" },
    features: ["Advanced formula", "High performance", "Flexible"],
    tags: ["tiling", "adhesive", "myk-laticrete"],
  },
];

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand?.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q))
  );
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}
