export interface Product {
  id: string;
  name: string;
  slug: string;
  sku: string;
  description: string;
  shortDescription: string;
  brand: string | null;
  brandSlug: string | null;
  category: string;
  categorySlug: string;
  subCategory: string | null;
  subCategorySlug: string | null;
  unit: string;
  unitCode: string;
  unitSymbol: string | null;
  price: number;
  mrp: number;
  discount: number;
  bulkPrice: number | null;
  bulkMinQty: number | null;
  bulkLabel: string | null;
  gstRate: number;
  gstCode: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  stockLevel: number;
  moq: number;
  deliveryDays: number;
  freeDelivery: boolean;
  seller: { name: string; rating: number; isVerified: boolean };
  images: string[];
  specifications: Record<string, string>;
  features: string[];
  tags: string[];
}

export interface Category {
  name: string;
  slug: string;
  description: string;
  icon: string;
  productCount: number;
  subCategories: { name: string; slug: string; productCount: number }[];
}

export const categories: Category[] = [
  { name: "Cement", slug: "cement", description: "OPC, PPC, Ready Mix", icon: "cement", productCount: 5, subCategories: [
    { name: "OPC Cement", slug: "opc", productCount: 2 },
    { name: "PPC Cement", slug: "ppc", productCount: 2 },
    { name: "Ready Mix", slug: "ready-mix", productCount: 1 },
  ]},
  { name: "Steel & TMT", slug: "steel-tmt", description: "Bars, Rods, Structural", icon: "steel", productCount: 5, subCategories: [
    { name: "TMT Bars", slug: "tmt-bars", productCount: 5 },
    { name: "Structural Steel", slug: "structural", productCount: 0 },
    { name: "Wire Rods", slug: "wire-rods", productCount: 0 },
  ]},
  { name: "Bricks & Blocks", slug: "bricks-blocks", description: "Fly Ash, AAC, Red Bricks", icon: "bricks", productCount: 3, subCategories: [
    { name: "Red Bricks", slug: "red-bricks", productCount: 1 },
    { name: "AAC Blocks", slug: "aac", productCount: 1 },
    { name: "Fly Ash Bricks", slug: "fly-ash", productCount: 1 },
  ]},
  { name: "Tiles & Ceramics", slug: "tiles-ceramics", description: "Floor, Wall, Parking", icon: "tiles", productCount: 12, subCategories: [
    { name: "Floor Tiles", slug: "floor", productCount: 5 },
    { name: "Wall Tiles", slug: "wall", productCount: 4 },
    { name: "Parking Tiles", slug: "parking", productCount: 3 },
  ]},
  { name: "Paint", slug: "paint", description: "Interior, Exterior, Primer", icon: "paint", productCount: 5, subCategories: [
    { name: "Exterior Paint", slug: "exterior", productCount: 3 },
    { name: "Interior Paint", slug: "interior", productCount: 2 },
    { name: "Primer", slug: "primer", productCount: 0 },
  ]},
  { name: "Electrical", slug: "electrical", description: "Wires, Switches, MCB", icon: "electrical", productCount: 5, subCategories: [
    { name: "Wires & Cables", slug: "wires", productCount: 3 },
    { name: "Switches", slug: "switches", productCount: 1 },
    { name: "MCB & Panels", slug: "mcb", productCount: 1 },
  ]},
  { name: "Plumbing", slug: "plumbing", description: "Pipes, Fittings, Tanks", icon: "plumbing", productCount: 5, subCategories: [
    { name: "PVC Pipes", slug: "pvc", productCount: 2 },
    { name: "CPVC Pipes", slug: "cpvc", productCount: 2 },
    { name: "SS Pipes", slug: "ss", productCount: 1 },
  ]},
  { name: "Sanitary & Bath", slug: "sanitary", description: "Faucets, Toilets, Basins", icon: "sanitary", productCount: 5, subCategories: [
    { name: "EWC / Commodes", slug: "ewc", productCount: 3 },
    { name: "Taps & Mixers", slug: "taps", productCount: 2 },
    { name: "Basins", slug: "basins", productCount: 0 },
  ]},
  { name: "Sand & Aggregate", slug: "sand-aggregate", description: "M Sand, River Sand, Gravel", icon: "sand", productCount: 3, subCategories: [
    { name: "River Sand", slug: "river-sand", productCount: 1 },
    { name: "M-Sand", slug: "m-sand", productCount: 2 },
  ]},
  { name: "Pipes & Fittings", slug: "pipes-fittings", description: "MS Pipes, ERW, GI", icon: "pipes", productCount: 3, subCategories: [
    { name: "MS Pipes", slug: "ms-pipes", productCount: 3 },
    { name: "GI Pipes", slug: "gi-pipes", productCount: 0 },
  ]},
  { name: "Plywood & Boards", slug: "plywood-boards", description: "Plywood, MDF, HDHMR", icon: "plywood", productCount: 4, subCategories: [
    { name: "Plywood", slug: "plywood", productCount: 3 },
    { name: "MDF Board", slug: "mdf", productCount: 1 },
  ]},
  { name: "Hardware", slug: "hardware", description: "Hinges, Locks, Fittings", icon: "hardware", productCount: 4, subCategories: [
    { name: "Hinges & Fittings", slug: "hinges", productCount: 3 },
    { name: "Locks", slug: "locks", productCount: 1 },
  ]},
];

export const products: Product[] = [
  // CEMENT
  {
    id: "cement-1",
    name: "UltraTech Cement OPC 53 Grade 50kg",
    slug: "ultratech-cement-opc-53",
    sku: "CEM-UT-OPC53",
    description: "UltraTech Cement OPC 53 Grade is a high-performance Portland cement conforming to IS 12269. It offers high early and ultimate compressive strength, making it ideal for structural concrete, pre-stressed concrete, and heavy-duty foundations. Consistent quality with advanced manufacturing process.",
    shortDescription: "High-strength OPC 53 grade cement for structural concrete",
    brand: "UltraTech",
    brandSlug: "ultratech",
    category: "Cement",
    categorySlug: "cement",
    subCategory: "OPC Cement",
    subCategorySlug: "opc",
    unit: "Bag (50 kg)",
    unitCode: "BAG",
    unitSymbol: null,
    price: 385,
    mrp: 410,
    discount: 6,
    bulkPrice: 365,
    bulkMinQty: 50,
    bulkLabel: "₹365 at 50+ bags",
    gstRate: 28,
    gstCode: "GST 28%",
    rating: 4.6,
    reviewCount: 567,
    inStock: true,
    stockLevel: 5000,
    moq: 10,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "UltraTech Cement Dealers", rating: 4.8, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Grade": "53 OPC", "Weight": "50 kg", "Compressive Strength (28 days)": "53 MPa", "Setting Time (Initial)": "30 min", "Fineness": "330 m²/kg", "Standard": "IS 12269:2013" },
    features: ["High early strength", "Consistent quality", "Low alkali content", "ISI marked"],
    tags: ["opc", "cement", "53-grade", "structural", "concrete"],
  },
  {
    id: "cement-2",
    name: "ACC Cement PPC 43 Grade 50kg",
    slug: "acc-cement-ppc-43",
    sku: "CEM-ACC-PPC43",
    description: "ACC Limited PPC 43 Grade cement is manufactured using high-quality clinker and fly ash. It offers excellent workability and durability, making it ideal for general construction, plastering, and masonry work. Environmentally friendly with fly ash content.",
    shortDescription: "PPC cement for general construction and plastering",
    brand: "ACC",
    brandSlug: "acc",
    category: "Cement",
    categorySlug: "cement",
    subCategory: "PPC Cement",
    subCategorySlug: "ppc",
    unit: "Bag (50 kg)",
    unitCode: "BAG",
    unitSymbol: null,
    price: 360,
    mrp: 395,
    discount: 9,
    bulkPrice: 340,
    bulkMinQty: 50,
    bulkLabel: "₹340 at 50+ bags",
    gstRate: 28,
    gstCode: "GST 28%",
    rating: 4.4,
    reviewCount: 342,
    inStock: true,
    stockLevel: 3500,
    moq: 10,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "ACC Cement Distributors", rating: 4.6, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Grade": "43 PPC", "Weight": "50 kg", "Compressive Strength (28 days)": "43 MPa", "Setting Time (Initial)": "30 min", "Standard": "IS 1489 Part 1:2015" },
    features: ["Fly ash based", "Better workability", "Sulphate resistant", "ISI marked"],
    tags: ["ppc", "cement", "43-grade", "plastering", "masonry"],
  },
  {
    id: "cement-3",
    name: "Ambuja Cement Strong 50kg",
    slug: "ambuja-cement-strong",
    sku: "CEM-AMB-STR",
    description: "Ambuja Cement Strong is a premium OPC 53 grade cement known for its superior strength and durability. Ideal for high-rise buildings, bridges, and heavy construction. Advanced grinding technology ensures fine particle size for better bonding.",
    shortDescription: "Premium OPC 53 grade for heavy construction",
    brand: "Ambuja",
    brandSlug: "ambuja",
    category: "Cement",
    categorySlug: "cement",
    subCategory: "Ready Mix",
    subCategorySlug: "ready-mix",
    unit: "Bag (50 kg)",
    unitCode: "BAG",
    unitSymbol: null,
    price: 370,
    mrp: 400,
    discount: 8,
    bulkPrice: 350,
    bulkMinQty: 50,
    bulkLabel: "₹350 at 50+ bags",
    gstRate: 28,
    gstCode: "GST 28%",
    rating: 4.3,
    reviewCount: 210,
    inStock: true,
    stockLevel: 2000,
    moq: 10,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "Ambuja Cement Hub", rating: 4.5, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Grade": "53 OPC", "Weight": "50 kg", "Compressive Strength (28 days)": "53 MPa", "Standard": "IS 12269:2013" },
    features: ["High strength", "Fine grinding", "Consistent quality", "ISI marked"],
    tags: ["opc", "cement", "53-grade", "heavy-construction"],
  },

  // STEEL & TMT
  {
    id: "steel-1",
    name: "Tata Tiscon TMT Bar 12mm Fe-500D",
    slug: "tata-tiscon-tmt-12mm",
    sku: "STL-TT-TMT12",
    description: "Tata Tiscon Fe-500D TMT bars are manufactured using the latest Thermex quenching technology. The unique rib pattern ensures superior bonding with concrete. High yield strength of 500 MPa with excellent ductility and weldability. Conforms to IS 1786:2008.",
    shortDescription: "Premium TMT bars with Thermex technology for RCC structures",
    brand: "Tata Tiscon",
    brandSlug: "tata-tiscon",
    category: "Steel & TMT",
    categorySlug: "steel-tmt",
    subCategory: "TMT Bars",
    subCategorySlug: "tmt-bars",
    unit: "Kilogram",
    unitCode: "KG",
    unitSymbol: "kg",
    price: 64,
    mrp: 68,
    discount: 6,
    bulkPrice: 60,
    bulkMinQty: 500,
    bulkLabel: "₹60 at 500+ kg",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.8,
    reviewCount: 892,
    inStock: true,
    stockLevel: 10000,
    moq: 100,
    deliveryDays: 2,
    freeDelivery: true,
    seller: { name: "Tata Steel Distribution", rating: 4.9, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Grade": "Fe-500D", "Diameter": "12mm", "Length": "12m", "Yield Strength": "500 MPa", "Tensile Strength": "565 MPa", "Elongation": "18%", "Standard": "IS 1786:2008", "Surface": "Corrugated" },
    features: ["Thermex quenching", "Superior bonding", "High ductility", "Corrosion resistant"],
    tags: ["tmt", "steel", "fe-500d", "12mm", "rcc"],
  },
  {
    id: "steel-2",
    name: "JSW Steel TMT Bar 16mm Fe-500D",
    slug: "jsw-steel-tmt-16mm",
    sku: "STL-JSW-TMT16",
    description: "JSW Steel Neosteel TMT bars are made from virgin iron ore using the Coreq technology. Fe-500D grade with high strength and excellent bendability. Ideal for columns, beams, and heavy structural applications.",
    shortDescription: "Coreq technology TMT bars for heavy structures",
    brand: "JSW Steel",
    brandSlug: "jsw-steel",
    category: "Steel & TMT",
    categorySlug: "steel-tmt",
    subCategory: "TMT Bars",
    subCategorySlug: "tmt-bars",
    unit: "Kilogram",
    unitCode: "KG",
    unitSymbol: "kg",
    price: 62,
    mrp: 66,
    discount: 6,
    bulkPrice: 58,
    bulkMinQty: 500,
    bulkLabel: "₹58 at 500+ kg",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.7,
    reviewCount: 654,
    inStock: true,
    stockLevel: 8000,
    moq: 100,
    deliveryDays: 2,
    freeDelivery: true,
    seller: { name: "JSW Steel Authorized Dealer", rating: 4.7, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Grade": "Fe-500D", "Diameter": "16mm", "Length": "12m", "Yield Strength": "500 MPa", "Tensile Strength": "565 MPa", "Elongation": "18%", "Standard": "IS 1786:2008" },
    features: ["Coreq technology", "Virgin iron ore", "High bendability", "Consistent quality"],
    tags: ["tmt", "steel", "fe-500d", "16mm", "columns"],
  },
  {
    id: "steel-3",
    name: "SAIL TMT Bar 10mm Fe-500D",
    slug: "sail-tmt-10mm",
    sku: "STL-SAIL-TMT10",
    description: "SAIL TMT bars manufactured with state-of-the-art quenching and tempering process. Fe-500D grade suitable for residential and commercial construction. Excellent weldability and corrosion resistance.",
    shortDescription: "Reliable TMT bars for residential construction",
    brand: "SAIL",
    brandSlug: "sail",
    category: "Steel & TMT",
    categorySlug: "steel-tmt",
    subCategory: "TMT Bars",
    subCategorySlug: "tmt-bars",
    unit: "Kilogram",
    unitCode: "KG",
    unitSymbol: "kg",
    price: 66,
    mrp: 70,
    discount: 6,
    bulkPrice: 62,
    bulkMinQty: 500,
    bulkLabel: "₹62 at 500+ kg",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.5,
    reviewCount: 321,
    inStock: true,
    stockLevel: 6000,
    moq: 100,
    deliveryDays: 2,
    freeDelivery: true,
    seller: { name: "SAIL Authorized Stockist", rating: 4.5, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Grade": "Fe-500D", "Diameter": "10mm", "Length": "12m", "Yield Strength": "500 MPa", "Standard": "IS 1786:2008" },
    features: ["Government quality", "Corrosion resistant", "Good weldability", "ISI marked"],
    tags: ["tmt", "steel", "fe-500d", "10mm", "residential"],
  },

  // BRICKS & BLOCKS
  {
    id: "bricks-1",
    name: "Red Clay Bricks First Class 9x4x3 inch",
    slug: "red-clay-bricks-first-class",
    sku: "BRK-RED-FC",
    description: "First class machine molded red clay bricks conforming to IS 1077. Uniform shape and size with high compressive strength. Ideal for load bearing walls, partition walls, and general masonry. Burnt in kilns for consistent quality.",
    shortDescription: "Machine molded red clay bricks for load bearing walls",
    brand: null,
    brandSlug: null,
    category: "Bricks & Blocks",
    categorySlug: "bricks-blocks",
    subCategory: "Red Bricks",
    subCategorySlug: "red-bricks",
    unit: "Piece",
    unitCode: "PCS",
    unitSymbol: null,
    price: 8.5,
    mrp: 10,
    discount: 15,
    bulkPrice: 7.5,
    bulkMinQty: 5000,
    bulkLabel: "₹7.5 at 5000+ pcs",
    gstRate: 5,
    gstCode: "GST 5%",
    rating: 4.2,
    reviewCount: 89,
    inStock: true,
    stockLevel: 100000,
    moq: 500,
    deliveryDays: 2,
    freeDelivery: false,
    seller: { name: "Bharat Bricks Supply Co.", rating: 4.3, isVerified: false },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "9 x 4 x 3 inch (228 x 107 x 75 mm)", "Compressive Strength": "10 MPa minimum", "Water Absorption": "20% max", "Class": "First Class", "Type": "Machine Molded" },
    features: ["ISI certified", "Uniform shape", "High compressive strength", "Weather resistant"],
    tags: ["bricks", "red-clay", "first-class", "load-bearing"],
  },
  {
    id: "bricks-2",
    name: "AAC Blocks 600x200x100mm",
    slug: "aac-blocks-600x200x100",
    sku: "BLK-AAC-600",
    description: "Autoclaved Aerated Concrete (AAC) blocks are lightweight, thermal insulating building blocks. 8 times lighter than regular bricks. Fire resistant up to 4 hours. Excellent sound insulation. Saves construction time and cost.",
    shortDescription: "Lightweight AAC blocks — 8x lighter than red bricks",
    brand: null,
    brandSlug: null,
    category: "Bricks & Blocks",
    categorySlug: "bricks-blocks",
    subCategory: "AAC Blocks",
    subCategorySlug: "aac",
    unit: "Piece",
    unitCode: "PCS",
    unitSymbol: null,
    price: 45,
    mrp: 55,
    discount: 18,
    bulkPrice: 40,
    bulkMinQty: 200,
    bulkLabel: "₹40 at 200+ pcs",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.4,
    reviewCount: 156,
    inStock: true,
    stockLevel: 20000,
    moq: 50,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "AAC Blocks India Pvt Ltd", rating: 4.5, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "600 x 200 x 100 mm", "Density": "550-650 kg/m³", "Compressive Strength": "3.5-4.5 MPa", "Thermal Conductivity": "0.12 W/mK", "Fire Rating": "4 hours" },
    features: ["8x lighter than bricks", "Fire resistant", "Thermal insulation", "Sound proof"],
    tags: ["aac", "blocks", "lightweight", "thermal", "insulation"],
  },
  {
    id: "bricks-3",
    name: "Fly Ash Bricks 230x110x75mm",
    slug: "fly-ash-bricks",
    sku: "BRK-FA-230",
    description: "Eco-friendly fly ash bricks made from industrial waste. Uniform size and shape with high compressive strength. Lower water absorption than red bricks. Cost-effective alternative for all types of construction.",
    shortDescription: "Eco-friendly fly ash bricks — uniform size, high strength",
    brand: null,
    brandSlug: null,
    category: "Bricks & Blocks",
    categorySlug: "bricks-blocks",
    subCategory: "Fly Ash Bricks",
    subCategorySlug: "fly-ash",
    unit: "Piece",
    unitCode: "PCS",
    unitSymbol: null,
    price: 6,
    mrp: 8,
    discount: 25,
    bulkPrice: 5,
    bulkMinQty: 10000,
    bulkLabel: "₹5 at 10000+ pcs",
    gstRate: 5,
    gstCode: "GST 5%",
    rating: 4.0,
    reviewCount: 67,
    inStock: true,
    stockLevel: 200000,
    moq: 1000,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Green Build Materials", rating: 4.2, isVerified: false },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "230 x 110 x 75 mm", "Compressive Strength": "10 MPa minimum", "Water Absorption": "12% max", "Material": "Fly Ash + Cement" },
    features: ["Eco-friendly", "Uniform size", "Low water absorption", "Cost effective"],
    tags: ["fly-ash", "bricks", "eco-friendly", "green-building"],
  },

  // TILES & CERAMICS
  {
    id: "tiles-1",
    name: "Kajaria Ceramic Floor Tiles 2x2 ft Polished",
    slug: "kajaria-floor-tiles-2x2",
    sku: "TLS-KAJ-FL2x2",
    description: "Premium Kajaria ceramic floor tiles with polished finish. Natural stone patterns with scratch and stain resistance. Suitable for living rooms, bedrooms, and commercial spaces. Easy to clean and maintain.",
    shortDescription: "Premium polished ceramic floor tiles by Kajaria",
    brand: "Kajaria",
    brandSlug: "kajaria",
    category: "Tiles & Ceramics",
    categorySlug: "tiles-ceramics",
    subCategory: "Floor Tiles",
    subCategorySlug: "floor",
    unit: "Square Foot",
    unitCode: "SQFT",
    unitSymbol: "ft²",
    price: 85,
    mrp: 100,
    discount: 15,
    bulkPrice: 75,
    bulkMinQty: 100,
    bulkLabel: "₹75 at 100+ sqft",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.7,
    reviewCount: 312,
    inStock: true,
    stockLevel: 5000,
    moq: 20,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Kajaria Premium Showroom", rating: 4.8, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "2 x 2 ft (600 x 600 mm)", "Thickness": "10-12mm", "Finish": "Polished", "Material": "Ceramic", "Water Absorption": "< 0.5%", "Application": "Flooring" },
    features: ["Scratch resistant", "Stain resistant", "Easy maintenance", "Premium finish"],
    tags: ["tiles", "floor", "kajaria", "ceramic", "polished"],
  },
  {
    id: "tiles-2",
    name: "Johnson Porcelain Wall Tiles 10x15 inch",
    slug: "johnson-wall-tiles-10x15",
    sku: "TLS-JOH-WL10x15",
    description: "Johnson porcelain wall tiles with elegant designs. High-definition digital printing for realistic patterns. Low maintenance, easy to clean. Perfect for kitchen backsplashes and bathroom walls.",
    shortDescription: "Digital printed porcelain wall tiles for kitchens and bathrooms",
    brand: "Johnson",
    brandSlug: "johnson",
    category: "Tiles & Ceramics",
    categorySlug: "tiles-ceramics",
    subCategory: "Wall Tiles",
    subCategorySlug: "wall",
    unit: "Square Foot",
    unitCode: "SQFT",
    unitSymbol: "ft²",
    price: 45,
    mrp: 55,
    discount: 18,
    bulkPrice: 38,
    bulkMinQty: 100,
    bulkLabel: "₹38 at 100+ sqft",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.5,
    reviewCount: 198,
    inStock: true,
    stockLevel: 3000,
    moq: 20,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Johnson Tiles Gallery", rating: 4.6, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "10 x 15 inch (250 x 375 mm)", "Finish": "Glossy", "Material": "Porcelain", "Water Absorption": "< 0.5%", "Application": "Wall" },
    features: ["Digital printing", "Glossy finish", "Easy to clean", "Fade resistant"],
    tags: ["tiles", "wall", "johnson", "porcelain", "kitchen"],
  },
  {
    id: "tiles-3",
    name: "Somany Digital Wall Tiles 2x2 ft",
    slug: "somany-digital-wall-tiles",
    sku: "TLS-SOM-DW2x2",
    description: "Somany digital wall tiles with ultra-high-definition printing technology. Available in marble and wood patterns. Scratch resistant glaze. Ideal for living rooms, bedrooms, and feature walls.",
    shortDescription: "UHD digital wall tiles with marble and wood patterns",
    brand: "Somany",
    brandSlug: "somany",
    category: "Tiles & Ceramics",
    categorySlug: "tiles-ceramics",
    subCategory: "Wall Tiles",
    subCategorySlug: "wall",
    unit: "Square Foot",
    unitCode: "SQFT",
    unitSymbol: "ft²",
    price: 95,
    mrp: 110,
    discount: 14,
    bulkPrice: 82,
    bulkMinQty: 100,
    bulkLabel: "₹82 at 100+ sqft",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.6,
    reviewCount: 245,
    inStock: true,
    stockLevel: 4000,
    moq: 20,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Somany Exclusive Store", rating: 4.7, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "600 x 600 mm", "Finish": "Matte", "Material": "Porcelain", "Application": "Wall & Floor" },
    features: ["UHD digital print", "Marble patterns", "Scratch resistant", "Matte finish"],
    tags: ["tiles", "wall", "somany", "digital", "marble"],
  },
  {
    id: "tiles-13",
    name: "Kajaria Vitrified Floor Tiles 2x4 ft",
    slug: "kajaria-vitrified-floor-tiles-2x4",
    sku: "TLS-KAJ-VF2x4",
    description: "Large-format vitrified floor tiles with a premium stone-look finish. Designed for high-traffic spaces, showrooms, and luxury homes with excellent stain and scratch resistance.",
    shortDescription: "Large-format vitrified floor tiles for premium interiors",
    brand: "Kajaria",
    brandSlug: "kajaria",
    category: "Tiles & Ceramics",
    categorySlug: "tiles-ceramics",
    subCategory: "Floor Tiles",
    subCategorySlug: "floor",
    unit: "Square Foot",
    unitCode: "SQFT",
    unitSymbol: "ft²",
    price: 118,
    mrp: 138,
    discount: 14,
    bulkPrice: 105,
    bulkMinQty: 200,
    bulkLabel: "₹105 at 200+ sqft",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.8,
    reviewCount: 164,
    inStock: true,
    stockLevel: 2600,
    moq: 30,
    deliveryDays: 4,
    freeDelivery: false,
    seller: { name: "Kajaria Large Format Center", rating: 4.9, isVerified: true },
    images: [
      "https://images.unsplash.com/photo-1565183928294-7063f23ce0f8?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1565183928294-7063f23ce0f8?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1565183928294-7063f23ce0f8?w=400&h=400&fit=crop",
    ],
    specifications: { "Size": "2 x 4 ft", "Thickness": "8-10mm", "Finish": "Glossy Vitrified", "Material": "Vitrified", "Water Absorption": "< 0.1%", "Application": "Flooring" },
    features: ["Large format", "Scratch resistant", "Luxury finish", "Low maintenance"],
    tags: ["tiles", "floor", "kajaria", "vitrified", "luxury"],
  },
  {
    id: "tiles-14",
    name: "Somany Anti-Skid Parking Tiles 12x12 in",
    slug: "somany-anti-skid-parking-tiles",
    sku: "TLS-SOM-PK12",
    description: "Heavy-duty anti-skid parking tiles engineered for driveways, ramps, and outdoor areas. High load-bearing capacity with textured grip and weather resistance.",
    shortDescription: "Anti-skid outdoor parking tiles with textured grip",
    brand: "Somany",
    brandSlug: "somany",
    category: "Tiles & Ceramics",
    categorySlug: "tiles-ceramics",
    subCategory: "Parking Tiles",
    subCategorySlug: "parking",
    unit: "Square Foot",
    unitCode: "SQFT",
    unitSymbol: "ft²",
    price: 72,
    mrp: 82,
    discount: 12,
    bulkPrice: 64,
    bulkMinQty: 250,
    bulkLabel: "₹64 at 250+ sqft",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.5,
    reviewCount: 118,
    inStock: true,
    stockLevel: 1800,
    moq: 40,
    deliveryDays: 4,
    freeDelivery: false,
    seller: { name: "Somany Outdoor Range", rating: 4.6, isVerified: true },
    images: [
      "https://images.unsplash.com/photo-1545243424-0ce743321e11?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1545243424-0ce743321e11?w=400&h=400&fit=crop",
      "https://images.unsplash.com/photo-1545243424-0ce743321e11?w=400&h=400&fit=crop",
    ],
    specifications: { "Size": "12 x 12 in", "Thickness": "14-16mm", "Finish": "Textured", "Material": "Ceramic", "Application": "Outdoor Flooring" },
    features: ["Anti-skid grip", "Weather resistant", "High load capacity", "Outdoor safe"],
    tags: ["tiles", "parking", "somany", "outdoor", "anti-skid"],
  },
  {
    id: "tiles-15",
    name: "Johnson Subway Wall Tiles 3x9 in",
    slug: "johnson-subway-wall-tiles",
    sku: "TLS-JOH-SUB39",
    description: "Classic subway-style wall tiles with a glossy surface for kitchens and bath backsplashes. Clean lines, easy installation, and low-maintenance performance.",
    shortDescription: "Classic subway wall tiles for kitchens and bathrooms",
    brand: "Johnson",
    brandSlug: "johnson",
    category: "Tiles & Ceramics",
    categorySlug: "tiles-ceramics",
    subCategory: "Wall Tiles",
    subCategorySlug: "wall",
    unit: "Square Foot",
    unitCode: "SQFT",
    unitSymbol: "ft²",
    price: 52,
    mrp: 61,
    discount: 15,
    bulkPrice: 45,
    bulkMinQty: 150,
    bulkLabel: "₹45 at 150+ sqft",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.4,
    reviewCount: 97,
    inStock: true,
    stockLevel: 2200,
    moq: 25,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Johnson Design Studio", rating: 4.5, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "3 x 9 in", "Finish": "Glossy", "Material": "Porcelain", "Application": "Wall", "Water Absorption": "< 0.5%" },
    features: ["Timeless design", "Easy to clean", "Glossy surface", "Kitchen friendly"],
    tags: ["tiles", "wall", "johnson", "subway", "porcelain"],
  },
  {
    id: "tiles-7",
    name: "Somany Marble Look Floor Tiles 2x2 ft",
    slug: "somany-marble-look-floor-tiles",
    sku: "TLS-SOM-ML2x2",
    description: "Marble-look floor tiles that combine premium aesthetics with the durability of vitrified surfaces. Ideal for living rooms, lobbies, and premium offices.",
    shortDescription: "Marble-look vitrified floor tiles for elegant interiors",
    brand: "Somany",
    brandSlug: "somany",
    category: "Tiles & Ceramics",
    categorySlug: "tiles-ceramics",
    subCategory: "Floor Tiles",
    subCategorySlug: "floor",
    unit: "Square Foot",
    unitCode: "SQFT",
    unitSymbol: "ft²",
    price: 104,
    mrp: 120,
    discount: 13,
    bulkPrice: 92,
    bulkMinQty: 120,
    bulkLabel: "₹92 at 120+ sqft",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.7,
    reviewCount: 204,
    inStock: true,
    stockLevel: 1700,
    moq: 24,
    deliveryDays: 4,
    freeDelivery: false,
    seller: { name: "Somany Marble Series", rating: 4.8, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "2 x 2 ft", "Finish": "Glossy", "Material": "Vitrified", "Water Absorption": "< 0.1%", "Application": "Flooring" },
    features: ["Marble aesthetic", "Vitrified strength", "High gloss", "Stain resistant"],
    tags: ["tiles", "floor", "somany", "marble", "vitrified"],
  },
  {
    id: "tiles-8",
    name: "Kajaria Wood Finish Wall Tiles 1x2 ft",
    slug: "kajaria-wood-finish-wall-tiles",
    sku: "TLS-KAJ-WD1x2",
    description: "Wood-finish wall tiles that bring warmth and texture without the maintenance of natural timber. Perfect for feature walls, cafes, and premium interiors.",
    shortDescription: "Wood-finish decorative wall tiles for feature walls",
    brand: "Kajaria",
    brandSlug: "kajaria",
    category: "Tiles & Ceramics",
    categorySlug: "tiles-ceramics",
    subCategory: "Wall Tiles",
    subCategorySlug: "wall",
    unit: "Square Foot",
    unitCode: "SQFT",
    unitSymbol: "ft²",
    price: 68,
    mrp: 79,
    discount: 14,
    bulkPrice: 60,
    bulkMinQty: 150,
    bulkLabel: "₹60 at 150+ sqft",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.6,
    reviewCount: 141,
    inStock: true,
    stockLevel: 2400,
    moq: 30,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Kajaria Decor Range", rating: 4.7, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "1 x 2 ft", "Finish": "Matte Texture", "Material": "Ceramic", "Application": "Wall", "Pattern": "Wood" },
    features: ["Wood texture", "Decorative finish", "Low maintenance", "Feature wall ready"],
    tags: ["tiles", "wall", "kajaria", "wood", "decorative"],
  },
  {
    id: "tiles-9",
    name: "Johnson Mosaic Accent Tiles 1x1 ft",
    slug: "johnson-mosaic-accent-tiles",
    sku: "TLS-JOH-MO1x1",
    description: "Mosaic accent tiles for borders, niches, and decorative strips. Small-format tile sheets with premium finish for kitchens, bathrooms, and lobbies.",
    shortDescription: "Decorative mosaic accent tiles for borders and niches",
    brand: "Johnson",
    brandSlug: "johnson",
    category: "Tiles & Ceramics",
    categorySlug: "tiles-ceramics",
    subCategory: "Wall Tiles",
    subCategorySlug: "wall",
    unit: "Square Foot",
    unitCode: "SQFT",
    unitSymbol: "ft²",
    price: 96,
    mrp: 112,
    discount: 14,
    bulkPrice: 84,
    bulkMinQty: 80,
    bulkLabel: "₹84 at 80+ sqft",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.5,
    reviewCount: 88,
    inStock: true,
    stockLevel: 900,
    moq: 10,
    deliveryDays: 4,
    freeDelivery: false,
    seller: { name: "Johnson Decor Studio", rating: 4.6, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "1 x 1 ft", "Finish": "Glossy", "Material": "Porcelain", "Application": "Accent / Border" },
    features: ["Accent styling", "Premium finish", "Decorative borders", "Easy installation"],
    tags: ["tiles", "accent", "johnson", "mosaic", "decor"],
  },

  // PAINT
  {
    id: "paint-1",
    name: "Asian Paints Apex Ultima 20L Exterior",
    slug: "asian-paints-apex-ultima-20l",
    sku: "PNT-AP-AU20",
    description: "Asian Paints Apex Ultima is a premium exterior emulsion with advanced Teflon surface protector. Provides complete protection against algae, fungus, and weather. Excellent coverage and colour retention for up to 10 years.",
    shortDescription: "Premium exterior emulsion with Teflon protection — 10 year life",
    brand: "Asian Paints",
    brandSlug: "asian-paints",
    category: "Paint",
    categorySlug: "paint",
    subCategory: "Exterior Paint",
    subCategorySlug: "exterior",
    unit: "Bucket (20 L)",
    unitCode: "BUCKET",
    unitSymbol: null,
    price: 2890,
    mrp: 3200,
    discount: 10,
    bulkPrice: 2750,
    bulkMinQty: 10,
    bulkLabel: "₹2,750 at 10+ buckets",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.7,
    reviewCount: 423,
    inStock: true,
    stockLevel: 500,
    moq: 1,
    deliveryDays: 2,
    freeDelivery: true,
    seller: { name: "Asian Paints Color World", rating: 4.8, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Volume": "20 Litre", "Type": "Exterior Emulsion", "Coverage": "50-60 sqft/litre", "Drying Time": "2-3 hours", "Coats": "2-3", "Life": "10 years" },
    features: ["Teflon surface protector", "Algae resistant", "10 year life", "UV resistant"],
    tags: ["paint", "exterior", "asian-paints", "emulsion", "weatherproof"],
  },
  {
    id: "paint-2",
    name: "Berger WeatherCoat All Guard 20L",
    slug: "berger-weathercoat-20l",
    sku: "PNT-BRG-WC20",
    description: "Berger WeatherCoat All Guard is a premium exterior paint with advanced acrylic technology. Provides superior weather protection, UV resistance, and anti-carbonation properties. Available in a wide range of shades.",
    shortDescription: "Advanced acrylic exterior paint with anti-carbonation",
    brand: "Berger",
    brandSlug: "berger",
    category: "Paint",
    categorySlug: "paint",
    subCategory: "Exterior Paint",
    subCategorySlug: "exterior",
    unit: "Bucket (20 L)",
    unitCode: "BUCKET",
    unitSymbol: null,
    price: 2450,
    mrp: 2800,
    discount: 13,
    bulkPrice: 2300,
    bulkMinQty: 10,
    bulkLabel: "₹2,300 at 10+ buckets",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.4,
    reviewCount: 187,
    inStock: true,
    stockLevel: 300,
    moq: 1,
    deliveryDays: 2,
    freeDelivery: true,
    seller: { name: "Berger Paints Dealer", rating: 4.5, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Volume": "20 Litre", "Type": "Exterior Emulsion", "Coverage": "50-55 sqft/litre", "Drying Time": "2-3 hours", "Coats": "2" },
    features: ["Anti-carbonation", "UV resistant", "Weather proof", "Wide shade range"],
    tags: ["paint", "exterior", "berger", "weatherproof"],
  },
  {
    id: "paint-3",
    name: "Nerolac Impressions XP 20L Interior",
    slug: "nerolac-impressions-xp-20l",
    sku: "PNT-NER-IXP20",
    description: "Nerolac Impressions XP is a premium interior emulsion with Silver Ion Technology for anti-bacterial protection. Low VOC, odourless. Provides smooth matte finish with excellent coverage. Safe for homes with children.",
    shortDescription: "Anti-bacterial interior emulsion — safe for children",
    brand: "Nerolac",
    brandSlug: "nerolac",
    category: "Paint",
    categorySlug: "paint",
    subCategory: "Interior Paint",
    subCategorySlug: "interior",
    unit: "Bucket (20 L)",
    unitCode: "BUCKET",
    unitSymbol: null,
    price: 2650,
    mrp: 2950,
    discount: 10,
    bulkPrice: 2500,
    bulkMinQty: 10,
    bulkLabel: "₹2,500 at 10+ buckets",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.5,
    reviewCount: 278,
    inStock: true,
    stockLevel: 400,
    moq: 1,
    deliveryDays: 2,
    freeDelivery: true,
    seller: { name: "Nerolac World of Colour", rating: 4.6, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Volume": "20 Litre", "Type": "Interior Emulsion", "Coverage": "55-60 sqft/litre", "Finish": "Matte", "Low VOC": "Yes" },
    features: ["Silver Ion Technology", "Anti-bacterial", "Low VOC", "Child safe"],
    tags: ["paint", "interior", "nerolac", "anti-bacterial", "child-safe"],
  },

  // ELECTRICAL
  {
    id: "electrical-1",
    name: "Havells LifeLine Plus 2.5sqmm Wire 90m",
    slug: "havells-lifeline-2-5sqmm",
    sku: "ELC-HAV-LL25",
    description: "Havells LifeLine Plus copper wires with FR-LSH (Flame Retardant Low Smoke Halogen-free) insulation. Superior conductivity with 99.97% pure electrolytic grade copper. Suitable for domestic and industrial wiring.",
    shortDescription: "FR-LSH copper wire with 99.97% pure copper",
    brand: "Havells",
    brandSlug: "havells",
    category: "Electrical",
    categorySlug: "electrical",
    subCategory: "Wires & Cables",
    subCategorySlug: "wires",
    unit: "Coil (90m)",
    unitCode: "COIL",
    unitSymbol: null,
    price: 2520,
    mrp: 2800,
    discount: 10,
    bulkPrice: 2400,
    bulkMinQty: 20,
    bulkLabel: "₹2,400 at 20+ coils",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.8,
    reviewCount: 534,
    inStock: true,
    stockLevel: 800,
    moq: 1,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "Havells authorized distributor", rating: 4.9, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "2.5 sq.mm", "Length": "90m", "Conductor": "99.97% Pure Copper", "Insulation": "FR-LSH", "Standard": "IS 694:2010", "Voltage Grade": "1100V" },
    features: ["99.97% pure copper", "FR-LSH insulation", "ISI marked", "Flame retardant"],
    tags: ["wires", "copper", "havells", "fr-lsh", "domestic"],
  },
  {
    id: "electrical-2",
    name: "Finolex FR Cable 2.5sqmm 90m",
    slug: "finolex-fr-cable-2-5sqmm",
    sku: "ELC-FIN-FR25",
    description: "Finolex FR (Flame Retardant) cable with heavy grade insulation. Copper conductor with 99.99% purity. Suitable for concealed wiring in residential and commercial buildings. Heat resistant up to 85°C.",
    shortDescription: "Heavy grade FR cable with 99.99% pure copper",
    brand: "Finolex",
    brandSlug: "finolex",
    category: "Electrical",
    categorySlug: "electrical",
    subCategory: "Wires & Cables",
    subCategorySlug: "wires",
    unit: "Coil (90m)",
    unitCode: "COIL",
    unitSymbol: null,
    price: 2880,
    mrp: 3200,
    discount: 10,
    bulkPrice: 2700,
    bulkMinQty: 25,
    bulkLabel: "₹2,700 at 25+ coils",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.7,
    reviewCount: 389,
    inStock: true,
    stockLevel: 600,
    moq: 1,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "Finolex Cables Dealer", rating: 4.7, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "2.5 sq.mm", "Length": "90m", "Conductor": "99.99% Pure Copper", "Insulation": "FR Grade", "Heat Resistance": "85°C", "Standard": "IS 694:2010" },
    features: ["99.99% pure copper", "Heat resistant 85°C", "Heavy insulation", "ISI marked"],
    tags: ["wires", "cable", "finolex", "flame-retardant", "concealed"],
  },
  {
    id: "electrical-3",
    name: "Polycab Optima Plus 1.5sqmm 90m",
    slug: "polycab-optima-1-5sqmm",
    sku: "ELC-POL-OP15",
    description: "Polycab Optima Plus HRFR (Heat Resistant Flame Retardant) wire. Electrolytic grade annealed copper conductor. Suitable for lighting circuits and low power applications. Lead-free PVC insulation.",
    shortDescription: "HRFR wire for lighting circuits — lead-free insulation",
    brand: "Polycab",
    brandSlug: "polycab",
    category: "Electrical",
    categorySlug: "electrical",
    subCategory: "Wires & Cables",
    subCategorySlug: "wires",
    unit: "Coil (90m)",
    unitCode: "COIL",
    unitSymbol: null,
    price: 1850,
    mrp: 2100,
    discount: 12,
    bulkPrice: 1750,
    bulkMinQty: 20,
    bulkLabel: "₹1,750 at 20+ coils",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.6,
    reviewCount: 267,
    inStock: true,
    stockLevel: 700,
    moq: 1,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "Polycab Wiring Solutions", rating: 4.6, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "1.5 sq.mm", "Length": "90m", "Conductor": "Annealed Copper", "Insulation": "Lead-free PVC", "Type": "HRFR", "Standard": "IS 694:2010" },
    features: ["Lead-free insulation", "HRFR rated", "Low smoke", "ISI marked"],
    tags: ["wires", "polycab", "hrfr", "lighting", "lead-free"],
  },

  // PLUMBING
  {
    id: "plumbing-1",
    name: "Supreme PVC Pipes 4 inch 6m",
    slug: "supreme-pvc-pipes-4inch",
    sku: "PLB-SUP-PVC4",
    description: "Supreme PVC pressure pipes for water supply, irrigation, and drainage. Lightweight, chemical resistant, and easy to install. Pressure rated for underground and above-ground applications.",
    shortDescription: "PVC pressure pipes for water supply and drainage",
    brand: "Supreme",
    brandSlug: "supreme",
    category: "Plumbing",
    categorySlug: "plumbing",
    subCategory: "PVC Pipes",
    subCategorySlug: "pvc",
    unit: "Piece (6m)",
    unitCode: "PCS",
    unitSymbol: null,
    price: 650,
    mrp: 750,
    discount: 13,
    bulkPrice: 580,
    bulkMinQty: 20,
    bulkLabel: "₹580 at 20+ pcs",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.3,
    reviewCount: 134,
    inStock: true,
    stockLevel: 500,
    moq: 5,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Supreme Pipe Gallery", rating: 4.4, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Diameter": "4 inch (110mm)", "Length": "6m", "Pressure Rating": "6 kg/cm²", "Type": "PVC", "Standard": "IS 4985:2000" },
    features: ["Chemical resistant", "Lightweight", "Easy install", "ISI marked"],
    tags: ["pipes", "pvc", "supreme", "water-supply", "drainage"],
  },
  {
    id: "plumbing-2",
    name: "Astral CPVC Pipes 1/2 inch 3m",
    slug: "astral-cpvc-pipes-half-inch",
    sku: "PLB-AST-CPVC05",
    description: "Astral CPVC pipes for hot and cold water distribution. Temperature resistant up to 95°C. Solvent cement joint for leak-proof connections. Ideal for residential and commercial plumbing.",
    shortDescription: "CPVC pipes for hot/cold water — heat resistant to 95°C",
    brand: "Astral",
    brandSlug: "astral",
    category: "Plumbing",
    categorySlug: "plumbing",
    subCategory: "CPVC Pipes",
    subCategorySlug: "cpvc",
    unit: "Piece (3m)",
    unitCode: "PCS",
    unitSymbol: null,
    price: 180,
    mrp: 220,
    discount: 18,
    bulkPrice: 160,
    bulkMinQty: 50,
    bulkLabel: "₹160 at 50+ pcs",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.5,
    reviewCount: 198,
    inStock: true,
    stockLevel: 1000,
    moq: 10,
    deliveryDays: 2,
    freeDelivery: false,
    seller: { name: "Astral Plumbing Solutions", rating: 4.6, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Diameter": "1/2 inch (15mm)", "Length": "3m", "Temperature Rating": "95°C", "Type": "CPVC", "Joint": "Solvent Cement" },
    features: ["Hot & cold water", "95°C rated", "Leak-proof", "ISI marked"],
    tags: ["pipes", "cpvc", "astral", "hot-water", "plumbing"],
  },
  {
    id: "plumbing-3",
    name: "Prince SS Pipes 2 inch 6m",
    slug: "prince-ss-pipes-2inch",
    sku: "PLB-PRI-SS2",
    description: "Prince stainless steel pipes for high-pressure water supply and industrial applications. Corrosion resistant, high strength, and long life. Suitable for both hot and cold water.",
    shortDescription: "Stainless steel pipes for high-pressure applications",
    brand: "Prince",
    brandSlug: "prince",
    category: "Plumbing",
    categorySlug: "plumbing",
    subCategory: "SS Pipes",
    subCategorySlug: "ss",
    unit: "Piece (6m)",
    unitCode: "PCS",
    unitSymbol: null,
    price: 850,
    mrp: 950,
    discount: 11,
    bulkPrice: 780,
    bulkMinQty: 20,
    bulkLabel: "₹780 at 20+ pcs",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.4,
    reviewCount: 89,
    inStock: true,
    stockLevel: 200,
    moq: 5,
    deliveryDays: 4,
    freeDelivery: false,
    seller: { name: "Prince Pipes Center", rating: 4.3, isVerified: false },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Diameter": "2 inch (50mm)", "Length": "6m", "Material": "Stainless Steel 304", "Pressure": "High" },
    features: ["Corrosion resistant", "High pressure", "Long life", "Industrial grade"],
    tags: ["pipes", "ss", "prince", "stainless", "high-pressure"],
  },

  // SANITARY & BATH
  {
    id: "sanitary-1",
    name: "Cera EWC Sanitary Ware",
    slug: "cera-ewc-sanitary-ware",
    sku: "SNT-CERA-EWC",
    description: "Cera EWC (European Water Closet) with rimless technology for easy cleaning. Single flush system with 3/6 litre dual flush. Anti-bacterial glaze. Soft close seat cover included.",
    shortDescription: "Rimless EWC with dual flush and anti-bacterial glaze",
    brand: "Cera",
    brandSlug: "cera",
    category: "Sanitary & Bath",
    categorySlug: "sanitary",
    subCategory: "EWC / Commodes",
    subCategorySlug: "ewc",
    unit: "Piece",
    unitCode: "PCS",
    unitSymbol: null,
    price: 7650,
    mrp: 8500,
    discount: 10,
    bulkPrice: 7200,
    bulkMinQty: 5,
    bulkLabel: "₹7,200 at 5+ pieces",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.5,
    reviewCount: 156,
    inStock: true,
    stockLevel: 50,
    moq: 1,
    deliveryDays: 3,
    freeDelivery: true,
    seller: { name: "Cera Sanitary Showroom", rating: 4.6, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Type": "EWC Floor Mounted", "Flush": "3/6L Dual Flush", "Technology": "Rimless", "Seat": "Soft Close", "Glaze": "Anti-bacterial" },
    features: ["Rimless cleaning", "Dual flush", "Anti-bacterial", "Soft close seat"],
    tags: ["sanitary", "ewc", "cera", "rimless", "dual-flush"],
  },
  {
    id: "sanitary-2",
    name: "Hindware Rimless EWC",
    slug: "hindware-rimless-ewc",
    sku: "SNT-HDW-RIM",
    description: "Hindware rimless EWC with intelligent flush system. Full flush and half flush options for water saving. German technology glaze for stain resistance. Suitable for all bathroom styles.",
    shortDescription: "German-glazed rimless EWC with intelligent flush",
    brand: "Hindware",
    brandSlug: "hindware",
    category: "Sanitary & Bath",
    categorySlug: "sanitary",
    subCategory: "EWC / Commodes",
    subCategorySlug: "ewc",
    unit: "Piece",
    unitCode: "PCS",
    unitSymbol: null,
    price: 6200,
    mrp: 7000,
    discount: 11,
    bulkPrice: 5800,
    bulkMinQty: 5,
    bulkLabel: "₹5,800 at 5+ pieces",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.3,
    reviewCount: 112,
    inStock: true,
    stockLevel: 35,
    moq: 1,
    deliveryDays: 3,
    freeDelivery: true,
    seller: { name: "Hindware Bathroom Studio", rating: 4.5, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Type": "EWC Floor Mounted", "Flush": "Intelligent Dual Flush", "Glaze": "German Technology", "Water Saving": "Yes" },
    features: ["German glaze", "Intelligent flush", "Water saving", "Stain resistant"],
    tags: ["sanitary", "ewc", "hindware", "rimless", "water-saving"],
  },
  {
    id: "sanitary-3",
    name: "Jaquar Basin Mixer Tap",
    slug: "jaquar-basin-mixer-tap",
    sku: "SNT-JAQ-BM01",
    description: "Jaquar basin mixer tap with single lever operation. Chrome finish with ceramic cartridge for drip-free performance. 5 year warranty. Suitable for all basin types.",
    shortDescription: "Single lever basin mixer with chrome finish and 5 year warranty",
    brand: "Jaquar",
    brandSlug: "jaquar",
    category: "Sanitary & Bath",
    categorySlug: "sanitary",
    subCategory: "Taps & Mixers",
    subCategorySlug: "taps",
    unit: "Piece",
    unitCode: "PCS",
    unitSymbol: null,
    price: 3500,
    mrp: 4200,
    discount: 17,
    bulkPrice: 3200,
    bulkMinQty: 3,
    bulkLabel: "₹3,200 at 3+ pieces",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.6,
    reviewCount: 234,
    inStock: true,
    stockLevel: 80,
    moq: 1,
    deliveryDays: 2,
    freeDelivery: true,
    seller: { name: "Jaquar Authorised Dealer", rating: 4.7, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Type": "Basin Mixer", "Operation": "Single Lever", "Finish": "Chrome", "Cartridge": "Ceramic", "Warranty": "5 Years" },
    features: ["Chrome finish", "Ceramic cartridge", "Drip free", "5 year warranty"],
    tags: ["taps", "mixer", "jaquar", "chrome", "basin"],
  },

  // SAND & AGGREGATE
  {
    id: "sand-1",
    name: "River Sand 0-20mm Clean",
    slug: "river-sand-0-20mm",
    sku: "SND-RVR-020",
    description: "Clean river sand graded 0-20mm for concrete mixing and plastering. Free from organic impurities, salt, and clay. Grading meets IS 383 standards. Suitable for all construction applications.",
    shortDescription: "Clean graded river sand for concrete and plastering",
    brand: null,
    brandSlug: null,
    category: "Sand & Aggregate",
    categorySlug: "sand-aggregate",
    subCategory: "River Sand",
    subCategorySlug: "river-sand",
    unit: "Metric Ton",
    unitCode: "MT",
    unitSymbol: "t",
    price: 2800,
    mrp: 3200,
    discount: 13,
    bulkPrice: 2600,
    bulkMinQty: 5,
    bulkLabel: "₹2,600 at 5+ MT",
    gstRate: 5,
    gstCode: "GST 5%",
    rating: 4.0,
    reviewCount: 45,
    inStock: true,
    stockLevel: 500,
    moq: 1,
    deliveryDays: 1,
    freeDelivery: false,
    seller: { name: "Kumar Sand Suppliers", rating: 4.2, isVerified: false },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Grading": "0-20mm", "Type": "River Sand", "Moisture Content": "< 5%", "Organic Impurities": "Nil", "Silt Content": "< 5%", "Fineness Modulus": "2.6-2.9" },
    features: ["IS 383 compliant", "No organic impurities", "Clean graded", "Consistent quality"],
    tags: ["sand", "river-sand", "concrete", "plastering"],
  },
  {
    id: "sand-2",
    name: "M-Sand 0-4.75mm Manufactured",
    slug: "m-sand-0-4-75mm",
    sku: "SND-MFG-047",
    description: "Manufactured sand (M-Sand) produced from crushed granite. Gradation IS 383 compliant. Zero silt content, no organic impurities. Better workability and strength compared to river sand.",
    shortDescription: "Crushed granite M-Sand — zero silt, better strength",
    brand: null,
    brandSlug: null,
    category: "Sand & Aggregate",
    categorySlug: "sand-aggregate",
    subCategory: "M-Sand",
    subCategorySlug: "m-sand",
    unit: "Metric Ton",
    unitCode: "MT",
    unitSymbol: "t",
    price: 2200,
    mrp: 2600,
    discount: 15,
    bulkPrice: 2000,
    bulkMinQty: 5,
    bulkLabel: "₹2,000 at 5+ MT",
    gstRate: 5,
    gstCode: "GST 5%",
    rating: 4.1,
    reviewCount: 78,
    inStock: true,
    stockLevel: 800,
    moq: 1,
    deliveryDays: 1,
    freeDelivery: false,
    seller: { name: "M-Sand Industries", rating: 4.3, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Grading": "0-4.75mm", "Type": "Manufactured Sand", "Silt Content": "Zero", "Source": "Crushed Granite", "Standard": "IS 383" },
    features: ["Zero silt", "Crushed granite", "Consistent gradation", "Eco-friendly"],
    tags: ["m-sand", "manufactured", "crushed", "eco-friendly"],
  },

  // PIPES & FITTINGS
  {
    id: "pipes-1",
    name: "Surya Roshni MS Pipe ERW 2 inch 6m",
    slug: "surya-roshni-ms-pipe-2inch",
    sku: "PIP-SUR-MS2",
    description: "Surya Roshni mild steel ERW (Electric Resistance Welded) pipes. High-quality weld seam with consistent wall thickness. Suitable for structural use, plumbing, and water supply lines. Conforms to IS 1239 Part 1.",
    shortDescription: "ERW MS pipes for structural and plumbing applications",
    brand: "Surya Roshni",
    brandSlug: "surya-roshni",
    category: "Pipes & Fittings",
    categorySlug: "pipes-fittings",
    subCategory: "MS Pipes",
    subCategorySlug: "ms-pipes",
    unit: "Piece (6m)",
    unitCode: "PCS",
    unitSymbol: null,
    price: 1250,
    mrp: 1400,
    discount: 11,
    bulkPrice: 1150,
    bulkMinQty: 20,
    bulkLabel: "₹1,150 at 20+ pcs",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.5,
    reviewCount: 123,
    inStock: true,
    stockLevel: 300,
    moq: 5,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Surya Roshni authorized distributor", rating: 4.6, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Diameter": "2 inch (50mm)", "Length": "6m", "Wall Thickness": "3.2mm", "Type": "ERW", "Standard": "IS 1239 Part 1", "Surface": "Black" },
    features: ["Consistent weld", "IS 1239 certified", "Multi-purpose", "Durable"],
    tags: ["pipes", "ms", "erw", "surya-roshni", "structural"],
  },
  {
    id: "pipes-2",
    name: "Tata Steel ERW Pipe 1.5 inch 6m",
    slug: "tata-steel-erw-pipe-1-5inch",
    sku: "PIP-TATA-ERW15",
    description: "Tata Steel ERW pipes manufactured with advanced technology. High strength with smooth finish. Suitable for structural applications, handrails, and water supply. Premium quality guaranteed.",
    shortDescription: "Premium ERW pipes from Tata Steel for structural use",
    brand: "Tata Steel",
    brandSlug: "tata-steel",
    category: "Pipes & Fittings",
    categorySlug: "pipes-fittings",
    subCategory: "MS Pipes",
    subCategorySlug: "ms-pipes",
    unit: "Piece (6m)",
    unitCode: "PCS",
    unitSymbol: null,
    price: 980,
    mrp: 1100,
    discount: 11,
    bulkPrice: 900,
    bulkMinQty: 20,
    bulkLabel: "₹900 at 20+ pcs",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.6,
    reviewCount: 98,
    inStock: true,
    stockLevel: 250,
    moq: 5,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Tata Steel Pipes Division", rating: 4.7, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Diameter": "1.5 inch (40mm)", "Length": "6m", "Wall Thickness": "2.9mm", "Type": "ERW", "Standard": "IS 1239 Part 1" },
    features: ["Tata quality", "Smooth finish", "High strength", "Structural grade"],
    tags: ["pipes", "erw", "tata-steel", "structural", "handrails"],
  },

  // PLYWOOD & BOARDS
  {
    id: "plywood-1",
    name: "Greenply BWR Plywood 19mm 8x4 ft",
    slug: "greenply-bwr-plywood-19mm",
    sku: "PLY-GRN-BWR19",
    description: "Greenply BWR (Boiling Water Resistant) grade plywood made from tropical hardwood veneers. Calibrated panels with consistent thickness. Borer and termite resistant. 15 year warranty.",
    shortDescription: "BWR grade plywood with 15 year warranty — borer resistant",
    brand: "Greenply",
    brandSlug: "greenply",
    category: "Plywood & Boards",
    categorySlug: "plywood-boards",
    subCategory: "Plywood",
    subCategorySlug: "plywood",
    unit: "Sheet (8x4 ft)",
    unitCode: "SHEET",
    unitSymbol: null,
    price: 3200,
    mrp: 3800,
    discount: 16,
    bulkPrice: 2950,
    bulkMinQty: 10,
    bulkLabel: "₹2,950 at 10+ sheets",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.6,
    reviewCount: 287,
    inStock: true,
    stockLevel: 150,
    moq: 1,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Greenply Dealer Network", rating: 4.7, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "8 x 4 ft (2440 x 1220 mm)", "Thickness": "19mm", "Grade": "BWR", "Material": "Tropical Hardwood", "Warranty": "15 Years" },
    features: ["BWR grade", "Borer resistant", "Calibrated", "15 year warranty"],
    tags: ["plywood", "greenply", "bwr", "hardwood", "furniture"],
  },
  {
    id: "plywood-2",
    name: "Century Plyboards Marine 12mm 8x4 ft",
    slug: "century-marine-plywood-12mm",
    sku: "PLY-CEN-MRN12",
    description: "Century Plyboards marine grade plywood for wet areas like kitchens and bathrooms. Boil proof grade with phenolic resin bonding. Water resistant for prolonged exposure. Suitable for underwater and marine applications.",
    shortDescription: "Marine grade plywood for kitchens, bathrooms, wet areas",
    brand: "Century Plyboards",
    brandSlug: "century-plyboards",
    category: "Plywood & Boards",
    categorySlug: "plywood-boards",
    subCategory: "Plywood",
    subCategorySlug: "plywood",
    unit: "Sheet (8x4 ft)",
    unitCode: "SHEET",
    unitSymbol: null,
    price: 2800,
    mrp: 3400,
    discount: 18,
    bulkPrice: 2600,
    bulkMinQty: 10,
    bulkLabel: "₹2,600 at 10+ sheets",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.4,
    reviewCount: 156,
    inStock: true,
    stockLevel: 100,
    moq: 1,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Century Ply Gallery", rating: 4.5, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "8 x 4 ft (2440 x 1220 mm)", "Thickness": "12mm", "Grade": "Marine", "Bonding": "Phenolic Resin", "Water Proof": "Boil Proof" },
    features: ["Marine grade", "Phenolic resin", "Water proof", "Kitchen safe"],
    tags: ["plywood", "century", "marine", "waterproof", "kitchen"],
  },

  // HARDWARE
  {
    id: "hardware-1",
    name: "Hettich Concealed Hinges Set of 2",
    slug: "hettich-concealed-hinges",
    sku: "HDW-HET-CH2",
    description: "Hettich concealed hinges for modular kitchen and wardrobe cabinets. 110° opening angle with soft-close mechanism. Nickel-plated steel construction. Tool-free clip mounting.",
    shortDescription: "Soft-close concealed hinges for modular cabinets",
    brand: "Hettich",
    brandSlug: "hettich",
    category: "Hardware",
    categorySlug: "hardware",
    subCategory: "Hinges & Fittings",
    subCategorySlug: "hinges",
    unit: "Set (2 pcs)",
    unitCode: "SET",
    unitSymbol: null,
    price: 280,
    mrp: 350,
    discount: 20,
    bulkPrice: 240,
    bulkMinQty: 20,
    bulkLabel: "₹240 at 20+ sets",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.7,
    reviewCount: 345,
    inStock: true,
    stockLevel: 500,
    moq: 1,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "Hettich Hardware Store", rating: 4.8, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Type": "Concealed Hinge", "Opening Angle": "110°", "Close Type": "Soft Close", "Material": "Nickel-plated Steel", "Mounting": "Clip-on" },
    features: ["Soft close", "110° opening", "Clip mounting", "Nickel plated"],
    tags: ["hinges", "hettich", "soft-close", "modular", "cabinet"],
  },
  {
    id: "hardware-2",
    name: "Godrej Mortise Lock Set",
    slug: "godrej-mortise-lock",
    sku: "HDW-GOD-ML1",
    description: "Godrej mortise lock set for main doors and bedrooms. 5-lever security with deadbolt. SS finish with anti-drill protection. Includes 3 keys, handle set, and night latch. ISI certified.",
    shortDescription: "5-lever mortise lock with anti-drill protection — ISI certified",
    brand: "Godrej",
    brandSlug: "godrej",
    category: "Hardware",
    categorySlug: "hardware",
    subCategory: "Locks",
    subCategorySlug: "locks",
    unit: "Set",
    unitCode: "SET",
    unitSymbol: null,
    price: 1800,
    mrp: 2200,
    discount: 18,
    bulkPrice: 1650,
    bulkMinQty: 5,
    bulkLabel: "₹1,650 at 5+ sets",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.8,
    reviewCount: 412,
    inStock: true,
    stockLevel: 120,
    moq: 1,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "Godrej Locking Solutions", rating: 4.9, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Type": "Mortise Lock", "Levers": "5-Lever", "Finish": "SS", "Protection": "Anti-drill", "Keys": "3 Included", "Standard": "ISI" },
    features: ["5-lever security", "Anti-drill", "ISI certified", "3 keys included"],
    tags: ["locks", "godrej", "mortise", "security", "door"],
  },

  // CEMENT - ADDITIONAL
  {
    id: "cement-4",
    name: "Birla White PPC Cement 50kg",
    slug: "birla-white-ppc-50kg",
    sku: "CEM-BIR-PPC",
    description: "Birla White PPC cement for superior white finish in plastering and painting. Excellent workability and smooth finish. Ideal for internal plastering, brickwork, and flooring.",
    shortDescription: "Premium white PPC cement for smooth plastering finish",
    brand: "Birla White",
    brandSlug: "birla-white",
    category: "Cement",
    categorySlug: "cement",
    subCategory: "PPC Cement",
    subCategorySlug: "ppc",
    unit: "Bag (50 kg)",
    unitCode: "BAG",
    unitSymbol: null,
    price: 420,
    mrp: 460,
    discount: 9,
    bulkPrice: 400,
    bulkMinQty: 50,
    bulkLabel: "₹400 at 50+ bags",
    gstRate: 28,
    gstCode: "GST 28%",
    rating: 4.5,
    reviewCount: 421,
    inStock: true,
    stockLevel: 4000,
    moq: 10,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "Birla Corporation Dealer", rating: 4.6, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Grade": "PPC", "Weight": "50 kg", "Compressive Strength (28 days)": "43 MPa", "Standard": "IS 1489 Part 1:2015" },
    features: ["White finish", "Smooth plastering", "ISI marked", "Fly ash based"],
    tags: ["ppc", "cement", "white", "plastering", "finish"],
  },
  {
    id: "cement-5",
    name: "Shree Cement UltraTech OPC 53 Grade 50kg",
    slug: "shree-cement-opc-53",
    sku: "CEM-SHR-OPC53",
    description: "Shree Cement OPC 53 grade for high-strength structural applications. Quick setting with high early strength. Cost-effective for bulk construction projects.",
    shortDescription: "High-strength OPC 53 for structural concrete applications",
    brand: "Shree Cement",
    brandSlug: "shree-cement",
    category: "Cement",
    categorySlug: "cement",
    subCategory: "OPC Cement",
    subCategorySlug: "opc",
    unit: "Bag (50 kg)",
    unitCode: "BAG",
    unitSymbol: null,
    price: 355,
    mrp: 395,
    discount: 10,
    bulkPrice: 335,
    bulkMinQty: 100,
    bulkLabel: "₹335 at 100+ bags",
    gstRate: 28,
    gstCode: "GST 28%",
    rating: 4.3,
    reviewCount: 287,
    inStock: true,
    stockLevel: 6000,
    moq: 10,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "Shree Cement Distributors", rating: 4.4, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Grade": "53 OPC", "Weight": "50 kg", "Compressive Strength (28 days)": "53 MPa", "Standard": "IS 12269:2013" },
    features: ["Quick setting", "High early strength", "Cost effective", "ISI marked"],
    tags: ["opc", "cement", "53-grade", "structural", "high-strength"],
  },

  // STEEL - ADDITIONAL
  {
    id: "steel-4",
    name: "Jindal Panther TMT 500D 16mm Bar",
    slug: "jindal-panther-tmt-16mm",
    sku: "STL-JDL-TMT16",
    description: "Jindal Panther Fe-500D TMT bars with advanced thermomechanical treatment. High yield strength and excellent ductility. Suitable for earthquake-resistant construction.",
    shortDescription: "Fe-500D TMT bars for earthquake-resistant structures",
    brand: "Jindal",
    brandSlug: "jindal",
    category: "Steel & TMT",
    categorySlug: "steel-tmt",
    subCategory: "TMT Bars",
    subCategorySlug: "tmt-bars",
    unit: "Kilogram",
    unitCode: "KG",
    unitSymbol: "kg",
    price: 63,
    mrp: 67,
    discount: 6,
    bulkPrice: 59,
    bulkMinQty: 500,
    bulkLabel: "₹59 at 500+ kg",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.6,
    reviewCount: 567,
    inStock: true,
    stockLevel: 9000,
    moq: 100,
    deliveryDays: 2,
    freeDelivery: true,
    seller: { name: "Jindal Steel Authorized Dealer", rating: 4.7, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Grade": "Fe-500D", "Diameter": "16mm", "Length": "12m", "Yield Strength": "500 MPa", "Standard": "IS 1786:2008" },
    features: ["Earthquake resistant", "High ductility", "Thermex treated", "ISI marked"],
    tags: ["tmt", "steel", "fe-500d", "16mm", "earthquake-resistant"],
  },
  {
    id: "steel-5",
    name: "Vizag TMT Bar 20mm Fe-500D",
    slug: "vizag-tmt-20mm",
    sku: "STL-VZG-TMT20",
    description: "Vizag TMT bars Fe-500D grade for heavy construction. Superior bonding with concrete due to rib pattern. Corrosion resistant with consistent quality.",
    shortDescription: "Heavy-duty TMT bars for large-scale construction projects",
    brand: "Vizag TMT",
    brandSlug: "vizag-tmt",
    category: "Steel & TMT",
    categorySlug: "steel-tmt",
    subCategory: "TMT Bars",
    subCategorySlug: "tmt-bars",
    unit: "Kilogram",
    unitCode: "KG",
    unitSymbol: "kg",
    price: 61,
    mrp: 65,
    discount: 6,
    bulkPrice: 57,
    bulkMinQty: 500,
    bulkLabel: "₹57 at 500+ kg",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.5,
    reviewCount: 423,
    inStock: true,
    stockLevel: 7000,
    moq: 100,
    deliveryDays: 2,
    freeDelivery: true,
    seller: { name: "Vizag Steel Plant Dealer", rating: 4.5, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Grade": "Fe-500D", "Diameter": "20mm", "Length": "12m", "Yield Strength": "500 MPa", "Standard": "IS 1786:2008" },
    features: ["Corrosion resistant", "Superior bonding", "Heavy construction", "ISI marked"],
    tags: ["tmt", "steel", "fe-500d", "20mm", "heavy-duty"],
  },

  // TILES - ADDITIONAL
  {
    id: "tiles-16",
    name: "Kajaria Digital Wall Tiles 2x3 ft",
    slug: "kajaria-digital-wall-tiles",
    sku: "TLS-KAJ-DW2x3",
    description: "Kajaria digital wall tiles with high-resolution printing. Marble look finish for premium interiors. Scratch resistant glaze suitable for kitchen and bathroom walls.",
    shortDescription: "Digital printed marble-look wall tiles for premium interiors",
    brand: "Kajaria",
    brandSlug: "kajaria",
    category: "Tiles & Ceramics",
    categorySlug: "tiles-ceramics",
    subCategory: "Wall Tiles",
    subCategorySlug: "wall",
    unit: "Square Foot",
    unitCode: "SQFT",
    unitSymbol: "ft²",
    price: 65,
    mrp: 85,
    discount: 24,
    bulkPrice: 55,
    bulkMinQty: 100,
    bulkLabel: "₹55 at 100+ sqft",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.6,
    reviewCount: 278,
    inStock: true,
    stockLevel: 4000,
    moq: 20,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Kajaria Premium Showroom", rating: 4.8, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "600 x 900 mm", "Finish": "Glossy", "Material": "Ceramic", "Water Absorption": "< 0.5%", "Application": "Wall" },
    features: ["Digital print", "Marble look", "Scratch resistant", "Premium finish"],
    tags: ["tiles", "wall", "kajaria", "digital", "marble"],
  },
  {
    id: "tiles-17",
    name: "Somany Floor Tiles 2x2 ft Anti-Skid",
    slug: "somany-antiskid-floor-tiles",
    sku: "TLS-SOM-AS2x2",
    description: "Somany anti-skid floor tiles with textured surface for safety. Suitable for bathrooms, balconies, and outdoor areas. High R-value slip resistance rating.",
    shortDescription: "Anti-skid textured floor tiles for wet and outdoor areas",
    brand: "Somany",
    brandSlug: "somany",
    category: "Tiles & Ceramics",
    categorySlug: "tiles-ceramics",
    subCategory: "Floor Tiles",
    subCategorySlug: "floor",
    unit: "Square Foot",
    unitCode: "SQFT",
    unitSymbol: "ft²",
    price: 72,
    mrp: 95,
    discount: 24,
    bulkPrice: 62,
    bulkMinQty: 100,
    bulkLabel: "₹62 at 100+ sqft",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.5,
    reviewCount: 198,
    inStock: true,
    stockLevel: 3500,
    moq: 20,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Somany Exclusive Store", rating: 4.7, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "600 x 600 mm", "Finish": "Matte Textured", "Material": "Porcelain", "Slip Rating": "R11", "Application": "Floor" },
    features: ["Anti-skid", "Textured surface", "Weather resistant", "Outdoor safe"],
    tags: ["tiles", "floor", "somany", "anti-skid", "outdoor"],
  },
  {
    id: "tiles-18",
    name: "Johnson Parking Tiles 12mm Heavy Duty",
    slug: "johnson-parking-tiles-12mm",
    sku: "TLS-JOH-PK12",
    description: "Johnson heavy-duty parking tiles 12mm thickness for car parking, driveways, and commercial spaces. High load bearing capacity with abrasion resistance.",
    shortDescription: "12mm heavy-duty parking tiles for driveways and commercial spaces",
    brand: "Johnson",
    brandSlug: "johnson",
    category: "Tiles & Ceramics",
    categorySlug: "tiles-ceramics",
    subCategory: "Floor Tiles",
    subCategorySlug: "floor",
    unit: "Square Foot",
    unitCode: "SQFT",
    unitSymbol: "ft²",
    price: 110,
    mrp: 140,
    discount: 21,
    bulkPrice: 95,
    bulkMinQty: 100,
    bulkLabel: "₹95 at 100+ sqft",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.4,
    reviewCount: 156,
    inStock: true,
    stockLevel: 2000,
    moq: 20,
    deliveryDays: 4,
    freeDelivery: false,
    seller: { name: "Johnson Tiles Gallery", rating: 4.6, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "600 x 600 mm", "Thickness": "12mm", "Finish": "Matte", "Load Rating": "Heavy Duty", "Application": "Parking/Driveway" },
    features: ["12mm thick", "Heavy load", "Abrasion resistant", "Commercial grade"],
    tags: ["tiles", "parking", "johnson", "heavy-duty", "driveway"],
  },

  // PAINT - ADDITIONAL
  {
    id: "paint-4",
    name: "Asian Paints Royale Luxury Interior 20L",
    slug: "asian-paints-royale-luxury-20l",
    sku: "PNT-AP-RL20",
    description: "Asian Paints Royale Luxury Interior emulsion with Teflon surface protector. Stain-free finish with anti-odour technology. Available in 1800+ shades.",
    shortDescription: "Premium luxury interior emulsion with Teflon and anti-stain tech",
    brand: "Asian Paints",
    brandSlug: "asian-paints",
    category: "Paint",
    categorySlug: "paint",
    subCategory: "Interior Paint",
    subCategorySlug: "interior",
    unit: "Bucket (20 L)",
    unitCode: "BUCKET",
    unitSymbol: null,
    price: 5200,
    mrp: 5800,
    discount: 10,
    bulkPrice: 4900,
    bulkMinQty: 5,
    bulkLabel: "₹4,900 at 5+ buckets",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.8,
    reviewCount: 567,
    inStock: true,
    stockLevel: 300,
    moq: 1,
    deliveryDays: 2,
    freeDelivery: true,
    seller: { name: "Asian Paints Color World", rating: 4.8, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Volume": "20 Litre", "Type": "Interior Emulsion", "Coverage": "55-60 sqft/litre", "Finish": "Matte", "Life": "8 years", "Shades": "1800+" },
    features: ["Teflon protector", "Anti-stain", "Anti-odour", "1800+ shades"],
    tags: ["paint", "interior", "asian-paints", "luxury", "royale"],
  },
  {
    id: "paint-5",
    name: "Dulux Weathershield 20L Exterior",
    slug: "dulux-weathershield-20l",
    sku: "PNT-DUX-WS20",
    description: "Dulux Weathershield exterior paint with Powerflexx technology. Flexes with wall surface to prevent cracking. All weather protection with UV blockers.",
    shortDescription: "Anti-crack exterior paint with Powerflexx technology",
    brand: "Dulux",
    brandSlug: "dulux",
    category: "Paint",
    categorySlug: "paint",
    subCategory: "Exterior Paint",
    subCategorySlug: "exterior",
    unit: "Bucket (20 L)",
    unitCode: "BUCKET",
    unitSymbol: null,
    price: 3100,
    mrp: 3500,
    discount: 11,
    bulkPrice: 2900,
    bulkMinQty: 5,
    bulkLabel: "₹2,900 at 5+ buckets",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.5,
    reviewCount: 312,
    inStock: true,
    stockLevel: 250,
    moq: 1,
    deliveryDays: 2,
    freeDelivery: true,
    seller: { name: "Dulux Paints Dealer", rating: 4.6, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Volume": "20 Litre", "Type": "Exterior Emulsion", "Coverage": "50-55 sqft/litre", "Technology": "Powerflexx", "Life": "7 years" },
    features: ["Anti-crack", "UV blockers", "All weather", "Flex technology"],
    tags: ["paint", "exterior", "dulux", "weatherproof", "anti-crack"],
  },

  // ELECTRICAL - ADDITIONAL
  {
    id: "electrical-4",
    name: "Havells MCB 32A Single Pole",
    slug: "havells-mcb-32a-sp",
    sku: "ELC-HAV-MCB32",
    description: "Havells MCB 32A single pole circuit breaker for overload and short circuit protection. C-curve tripping characteristic suitable for residential and commercial use.",
    shortDescription: "32A single pole MCB for residential circuit protection",
    brand: "Havells",
    brandSlug: "havells",
    category: "Electrical",
    categorySlug: "electrical",
    subCategory: "MCB & Panels",
    subCategorySlug: "mcb",
    unit: "Piece",
    unitCode: "PCS",
    unitSymbol: null,
    price: 185,
    mrp: 220,
    discount: 16,
    bulkPrice: 165,
    bulkMinQty: 20,
    bulkLabel: "₹165 at 20+ pcs",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.7,
    reviewCount: 234,
    inStock: true,
    stockLevel: 2000,
    moq: 1,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "Havells authorized distributor", rating: 4.9, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Rating": "32 Amp", "Poles": "Single Pole", "Curve": "C-Curve", "Breaking Capacity": "10kA", "Standard": "IS 8828" },
    features: ["Overload protection", "Short circuit protection", "ISI marked", "10kA breaking"],
    tags: ["mcb", "havells", "circuit-breaker", "protection", "electrical"],
  },
  {
    id: "electrical-5",
    name: "Anchor Roma Modular Switch Plate 6M",
    slug: "anchor-roma-6m-plate",
    sku: "ELC-ANC-RM6M",
    description: "Anchor Roma modular switch plate 6-module in elegant white finish. Made from polycarbonate with fire retardant properties. Compatible with all Roma modules.",
    shortDescription: "6-module polycarbonate switch plate with fire retardant body",
    brand: "Anchor",
    brandSlug: "anchor",
    category: "Electrical",
    categorySlug: "electrical",
    subCategory: "Switches",
    subCategorySlug: "switches",
    unit: "Piece",
    unitCode: "PCS",
    unitSymbol: null,
    price: 85,
    mrp: 110,
    discount: 23,
    bulkPrice: 75,
    bulkMinQty: 50,
    bulkLabel: "₹75 at 50+ pcs",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.5,
    reviewCount: 456,
    inStock: true,
    stockLevel: 5000,
    moq: 1,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "Anchor Electricals Dealer", rating: 4.7, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Modules": "6", "Material": "Polycarbonate", "Finish": "White", "Fire Rating": "V-0", "Standard": "IS 8623" },
    features: ["Fire retardant", "Polycarbonate", "Modular design", "ISI marked"],
    tags: ["switch", "anchor", "modular", "plate", "electrical"],
  },

  // PLUMBING - ADDITIONAL
  {
    id: "plumbing-4",
    name: "Ashirvad PVC Pressure Pipe 2 inch 6m",
    slug: "ashirvad-pvc-pressure-2inch",
    sku: "PLB-ASH-PVC2",
    description: "Ashirvad PVC pressure pipes for agricultural and industrial water supply. UV stabilized for outdoor use. Pressure rated up to 10 kg/cm².",
    shortDescription: "UV-stabilized PVC pressure pipes for agricultural supply",
    brand: "Ashirvad",
    brandSlug: "ashirvad",
    category: "Plumbing",
    categorySlug: "plumbing",
    subCategory: "PVC Pipes",
    subCategorySlug: "pvc",
    unit: "Piece (6m)",
    unitCode: "PCS",
    unitSymbol: null,
    price: 520,
    mrp: 620,
    discount: 16,
    bulkPrice: 460,
    bulkMinQty: 20,
    bulkLabel: "₹460 at 20+ pcs",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.4,
    reviewCount: 167,
    inStock: true,
    stockLevel: 800,
    moq: 5,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Ashirvad Pipes Gallery", rating: 4.5, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Diameter": "2 inch (63mm)", "Length": "6m", "Pressure Rating": "10 kg/cm²", "Type": "PVC", "UV Stabilized": "Yes" },
    features: ["UV stabilized", "High pressure", "Agricultural grade", "ISI marked"],
    tags: ["pipes", "pvc", "ashirvad", "agricultural", "pressure"],
  },
  {
    id: "plumbing-5",
    name: "Cera CPVC Elbow 1/2 inch Set of 10",
    slug: "cera-cpvc-elbow-half-inch",
    sku: "PLB-CRA-CPVC05E",
    description: "Cera CPVC elbow fittings 1/2 inch for hot and cold water piping. Solvent cement joint. Temperature resistant up to 95°C. ISI certified.",
    shortDescription: "CPVC elbow fittings for hot/cold water solvent cement joint",
    brand: "Cera",
    brandSlug: "cera",
    category: "Plumbing",
    categorySlug: "plumbing",
    subCategory: "CPVC Pipes",
    subCategorySlug: "cpvc",
    unit: "Set (10 pcs)",
    unitCode: "SET",
    unitSymbol: null,
    price: 145,
    mrp: 180,
    discount: 19,
    bulkPrice: 125,
    bulkMinQty: 20,
    bulkLabel: "₹125 at 20+ sets",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.6,
    reviewCount: 289,
    inStock: true,
    stockLevel: 3000,
    moq: 1,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "Cera Plumbing Solutions", rating: 4.6, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "1/2 inch (15mm)", "Type": "Elbow 90°", "Joint": "Solvent Cement", "Temperature": "95°C", "Standard": "IS 15778" },
    features: ["95°C rated", "Solvent joint", "Leak-proof", "ISI certified"],
    tags: ["fittings", "cpvc", "cera", "elbow", "plumbing"],
  },

  // SANITARY - ADDITIONAL
  {
    id: "sanitary-4",
    name: "Jaquar Basin Mixer Tap Concealed",
    slug: "jaquar-concealed-basin-mixer",
    sku: "SNT-JAQ-CBM01",
    description: "Jaquar concealed basin mixer with wall-mounted design. Chrome finish with quarter-turn ceramic cartridge. Single lever operation for temperature and flow control.",
    shortDescription: "Wall-mounted concealed basin mixer with chrome finish",
    brand: "Jaquar",
    brandSlug: "jaquar",
    category: "Sanitary & Bath",
    categorySlug: "sanitary",
    subCategory: "Taps & Mixers",
    subCategorySlug: "taps",
    unit: "Piece",
    unitCode: "PCS",
    unitSymbol: null,
    price: 4200,
    mrp: 5000,
    discount: 16,
    bulkPrice: 3800,
    bulkMinQty: 3,
    bulkLabel: "₹3,800 at 3+ pieces",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.7,
    reviewCount: 189,
    inStock: true,
    stockLevel: 60,
    moq: 1,
    deliveryDays: 2,
    freeDelivery: true,
    seller: { name: "Jaquar Authorised Dealer", rating: 4.7, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Type": "Concealed Basin Mixer", "Finish": "Chrome", "Operation": "Single Lever", "Cartridge": "Quarter Turn Ceramic", "Mount": "Wall" },
    features: ["Wall mounted", "Chrome finish", "Quarter turn", "5 year warranty"],
    tags: ["taps", "mixer", "jaquar", "concealed", "basin"],
  },
  {
    id: "sanitary-5",
    name: "Hindware Floor Mounted EWC Dual Flush",
    slug: "hindware-floor-ewc-dual",
    sku: "SNT-HDW-FEWC",
    description: "Hindware floor-mounted EWC with dual flush system. Full flush 6L and half flush 3L for water saving. Glossy white finish with anti-bacterial coating.",
    shortDescription: "Floor-mounted dual flush EWC with anti-bacterial coating",
    brand: "Hindware",
    brandSlug: "hindware",
    category: "Sanitary & Bath",
    categorySlug: "sanitary",
    subCategory: "EWC / Commodes",
    subCategorySlug: "ewc",
    unit: "Piece",
    unitCode: "PCS",
    unitSymbol: null,
    price: 5400,
    mrp: 6200,
    discount: 13,
    bulkPrice: 4900,
    bulkMinQty: 3,
    bulkLabel: "₹4,900 at 3+ pieces",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.4,
    reviewCount: 134,
    inStock: true,
    stockLevel: 40,
    moq: 1,
    deliveryDays: 3,
    freeDelivery: true,
    seller: { name: "Hindware Bathroom Studio", rating: 4.5, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Type": "EWC Floor Mounted", "Flush": "3/6L Dual", "Coating": "Anti-bacterial", "Finish": "Glossy White", "Water Saving": "Yes" },
    features: ["Dual flush", "Anti-bacterial", "Water saving", "Glossy finish"],
    tags: ["sanitary", "ewc", "hindware", "dual-flush", "floor-mounted"],
  },

  // PLYWOOD - ADDITIONAL
  {
    id: "plywood-3",
    name: "Kitply Plywood BWR 12mm 8x4 ft",
    slug: "kitply-bwr-plywood-12mm",
    sku: "PLY-KIT-BWR12",
    description: "Kitply BWR grade plywood with phenolic resin bonding. Calibrated panels for furniture and cabinetry. Borer and termite treated. 10 year warranty.",
    shortDescription: "BWR grade plywood for furniture — borer treated, 10yr warranty",
    brand: "Kitply",
    brandSlug: "kitply",
    category: "Plywood & Boards",
    categorySlug: "plywood-boards",
    subCategory: "Plywood",
    subCategorySlug: "plywood",
    unit: "Sheet (8x4 ft)",
    unitCode: "SHEET",
    unitSymbol: null,
    price: 2200,
    mrp: 2700,
    discount: 19,
    bulkPrice: 2000,
    bulkMinQty: 10,
    bulkLabel: "₹2,000 at 10+ sheets",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.3,
    reviewCount: 198,
    inStock: true,
    stockLevel: 200,
    moq: 1,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Kitply Dealer Network", rating: 4.4, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "8 x 4 ft", "Thickness": "12mm", "Grade": "BWR", "Bonding": "Phenolic Resin", "Warranty": "10 Years" },
    features: ["BWR grade", "Borer treated", "Calibrated", "10 year warranty"],
    tags: ["plywood", "kitply", "bwr", "furniture", "calibrated"],
  },
  {
    id: "plywood-4",
    name: "Century MDF Board 18mm 8x4 ft",
    slug: "century-mdf-board-18mm",
    sku: "PLY-CEN-MDF18",
    description: "Century MDF (Medium Density Fibreboard) board for modular furniture and interior design. Smooth surface for laminates and veneers. Consistent density throughout.",
    shortDescription: "18mm MDF board for modular furniture and interior panels",
    brand: "Century Plyboards",
    brandSlug: "century-plyboards",
    category: "Plywood & Boards",
    categorySlug: "plywood-boards",
    subCategory: "Plywood",
    subCategorySlug: "plywood",
    unit: "Sheet (8x4 ft)",
    unitCode: "SHEET",
    unitSymbol: null,
    price: 1450,
    mrp: 1800,
    discount: 19,
    bulkPrice: 1300,
    bulkMinQty: 10,
    bulkLabel: "₹1,300 at 10+ sheets",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.4,
    reviewCount: 167,
    inStock: true,
    stockLevel: 250,
    moq: 1,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "Century Ply Gallery", rating: 4.5, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "8 x 4 ft", "Thickness": "18mm", "Type": "MDF", "Density": "720-750 kg/m³", "Surface": "Smooth" },
    features: ["Smooth surface", "Consistent density", "Easy machining", "Laminate ready"],
    tags: ["mdf", "century", "furniture", "interior", "modular"],
  },

  // SAND - ADDITIONAL
  {
    id: "sand-3",
    name: "Crushed Stone Aggregate 20mm",
    slug: "crushed-stone-aggregate-20mm",
    sku: "SND-AGG-20",
    description: "Crushed stone aggregate 20mm for concrete mixing and road construction. IS 383 compliant grading. Hard and durable with low flakiness index.",
    shortDescription: "20mm crushed aggregate for concrete and road construction",
    brand: null,
    brandSlug: null,
    category: "Sand & Aggregate",
    categorySlug: "sand-aggregate",
    subCategory: "M-Sand",
    subCategorySlug: "m-sand",
    unit: "Metric Ton",
    unitCode: "MT",
    unitSymbol: "t",
    price: 1800,
    mrp: 2200,
    discount: 18,
    bulkPrice: 1600,
    bulkMinQty: 5,
    bulkLabel: "₹1,600 at 5+ MT",
    gstRate: 5,
    gstCode: "GST 5%",
    rating: 4.2,
    reviewCount: 89,
    inStock: true,
    stockLevel: 1000,
    moq: 1,
    deliveryDays: 1,
    freeDelivery: false,
    seller: { name: "Aggregates India Pvt Ltd", rating: 4.3, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Size": "20mm", "Type": "Crushed Stone", "Flakiness Index": "< 30%", "Standard": "IS 383", "Bulk Density": "1.5-1.6 t/m³" },
    features: ["IS 383 compliant", "Low flakiness", "Hard & durable", "Concrete grade"],
    tags: ["aggregate", "crushed", "stone", "concrete", "20mm"],
  },

  // PIPES - ADDITIONAL
  {
    id: "pipes-3",
    name: "APL Apollo GI Pipe 1.5 inch 6m",
    slug: "apl-apollo-gi-pipe-1-5inch",
    sku: "PIP-APL-GI15",
    description: "APL Apollo galvanized iron (GI) pipe for water supply and fire fighting systems. Hot-dip galvanized for corrosion resistance. IS 1239 certified.",
    shortDescription: "Galvanized iron pipe for water supply and fire fighting",
    brand: "APL Apollo",
    brandSlug: "apl-apollo",
    category: "Pipes & Fittings",
    categorySlug: "pipes-fittings",
    subCategory: "MS Pipes",
    subCategorySlug: "ms-pipes",
    unit: "Piece (6m)",
    unitCode: "PCS",
    unitSymbol: null,
    price: 1100,
    mrp: 1250,
    discount: 12,
    bulkPrice: 1000,
    bulkMinQty: 20,
    bulkLabel: "₹1,000 at 20+ pcs",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.5,
    reviewCount: 145,
    inStock: true,
    stockLevel: 350,
    moq: 5,
    deliveryDays: 3,
    freeDelivery: false,
    seller: { name: "APL Apollo Pipes Distributor", rating: 4.6, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Diameter": "1.5 inch (40mm)", "Length": "6m", "Type": "GI", "Coating": "Hot-dip Galvanized", "Standard": "IS 1239 Part 1" },
    features: ["Corrosion resistant", "Galvanized", "Fire fighting grade", "ISI marked"],
    tags: ["pipes", "gi", "apl-apollo", "galvanized", "fire-fighting"],
  },

  // HARDWARE - ADDITIONAL
  {
    id: "hardware-3",
    name: "Ebco Sliding Channel 350mm Set",
    slug: "ebco-sliding-channel-350mm",
    sku: "HDW-EBC-SC350",
    description: "Ebco ball bearing sliding channel for drawer systems. 350mm length with full extension. Load capacity 45kg per pair. Soft-close compatible.",
    shortDescription: "350mm full extension drawer channel with 45kg load capacity",
    brand: "Ebco",
    brandSlug: "ebco",
    category: "Hardware",
    categorySlug: "hardware",
    subCategory: "Hinges & Fittings",
    subCategorySlug: "hinges",
    unit: "Set (2 pcs)",
    unitCode: "SET",
    unitSymbol: null,
    price: 420,
    mrp: 520,
    discount: 19,
    bulkPrice: 370,
    bulkMinQty: 20,
    bulkLabel: "₹370 at 20+ sets",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.6,
    reviewCount: 234,
    inStock: true,
    stockLevel: 600,
    moq: 1,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "Ebco Hardware Store", rating: 4.7, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Length": "350mm", "Extension": "Full", "Load Capacity": "45 kg/pair", "Type": "Ball Bearing", "Soft Close": "Compatible" },
    features: ["Full extension", "Ball bearing", "45kg load", "Soft close ready"],
    tags: ["hardware", "ebco", "drawer", "channel", "sliding"],
  },
  {
    id: "hardware-4",
    name: "Hettich Soft Close Hinges Set of 4",
    slug: "hettich-softclose-hinges-4set",
    sku: "HDW-HET-SC4",
    description: "Hettich soft close hinges for kitchen and wardrobe shutters. 110° opening with integrated damping mechanism. Tool-free 3D adjustment. Nickel plated.",
    shortDescription: "Soft close hinges with 3D adjustment for kitchen cabinets",
    brand: "Hettich",
    brandSlug: "hettich",
    category: "Hardware",
    categorySlug: "hardware",
    subCategory: "Hinges & Fittings",
    subCategorySlug: "hinges",
    unit: "Set (4 pcs)",
    unitCode: "SET",
    unitSymbol: null,
    price: 580,
    mrp: 720,
    discount: 19,
    bulkPrice: 510,
    bulkMinQty: 20,
    bulkLabel: "₹510 at 20+ sets",
    gstRate: 18,
    gstCode: "GST 18%",
    rating: 4.7,
    reviewCount: 312,
    inStock: true,
    stockLevel: 800,
    moq: 1,
    deliveryDays: 1,
    freeDelivery: true,
    seller: { name: "Hettich Hardware Store", rating: 4.8, isVerified: true },
    images: [
      "/modit-placeholder.svg",
      "/modit-placeholder.svg",
    ],
    specifications: { "Type": "Soft Close Hinge", "Opening Angle": "110°", "Adjustment": "3D Tool-free", "Material": "Nickel-plated Steel", "Set": "4 pcs" },
    features: ["Soft close", "3D adjustment", "Tool-free", "Integrated damping"],
    tags: ["hinges", "hettich", "soft-close", "kitchen", "3d-adjustment"],
  },
];

export const brands = [
  "UltraTech", "ACC", "Ambuja", "Birla White", "Shree Cement",
  "Tata Tiscon", "JSW Steel", "SAIL", "Jindal", "Vizag TMT",
  "Kajaria", "Johnson", "Somany", "Asian Paints", "Berger", "Nerolac", "Dulux",
  "Havells", "Finolex", "Polycab", "Anchor",
  "Supreme", "Astral", "Prince", "Ashirvad",
  "Cera", "Hindware", "Jaquar",
  "Greenply", "Century Plyboards", "Kitply",
  "Hettich", "Godrej", "Ebco",
  "Surya Roshni", "Tata Steel", "APL Apollo",
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(slug: string): Product[] {
  return products.filter((p) => p.categorySlug === slug);
}

export function getProductsByBrand(slug: string): Product[] {
  return products.filter((p) => p.brandSlug === slug);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand?.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q))
  );
}

export function getCategories(): Category[] {
  return categories;
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}
