import type { LayoutResponse } from "@/lib/layout-types";

export const STATIC_HOME_LAYOUT: LayoutResponse = {
  version: "1.0",
  screen: "home",
  meta: {
    pincode: "201301",
    city: "New Delhi",
    eta: "60 mins",
    is_serviceable: true,
    user_segment: "all",
  },
  sections: [
    {
      type: "DeliveryBar",
      id: "delivery_bar_001",
      order: 0,
      visible: true,
      data: { eta_minutes: 60, pincode: "201301", city: "New Delhi", is_serviceable: true },
    },
    {
      type: "DispatchBanner",
      id: "dispatch_banner_001",
      order: 1,
      visible: true,
      data: { dispatch_time: "8 AM", dispatch_date: "20 August 2026" },
    },
    {
      type: "PromoBanner",
      id: "promo_banner_001",
      order: 2,
      visible: true,
      data: {
        title: "FREE DELIVERY",
        subtitle: "Free Delivery on next 5 orders",
        badge_text: "(Valid till 31-Jul)",
        badge_color: "#E91E63",
        bg_gradient: "from-[#2D1B69] to-[#4A2D8A]",
        valid_till: "2026-07-31",
      },
    },
    {
      type: "AssuredStrip",
      id: "assured_strip_001",
      order: 3,
      visible: true,
      data: {
        title: "Modit Assured",
        features: [
          { title: "7 Day Replacement", description: "Over & Above Brand Warranty", icon: "RotateCcw", color: "#E91E63" },
          { title: "4 Hour Resolution", description: "On Any Quality Issues", icon: "Clock", color: "#7CB518" },
          { title: "100% Genuine Guarantee", description: "QR Code & Batch Number Verified", icon: "CircleCheck", color: "#7CB518" },
          { title: "Easy Returns", description: "No Questions Asked", icon: "Package", color: "#E91E63" },
        ],
      },
    },
    {
      type: "CategoryGrid",
      id: "category_grid_001",
      order: 4,
      visible: true,
      data: {
        columns: 4,
        categories: [
          { id: "1", name: "Cement", slug: "cement", image_url: "https://images.unsplash.com/photo-1680357680725-f350480aee35?w=200&h=200&fit=crop", product_count: 500 },
          { id: "2", name: "Tiling", slug: "tiles-ceramics", image_url: "https://images.unsplash.com/photo-1615876302829-924be67e3a8e?w=200&h=200&fit=crop", product_count: 1200 },
          { id: "3", name: "Painting", slug: "paint", image_url: "https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=200&h=200&fit=crop", product_count: 800 },
          { id: "4", name: "Water Proofing", slug: "waterproofing", image_url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=200&h=200&fit=crop", product_count: 100 },
          { id: "5", name: "Plywood, MDF\n& HDHMR", slug: "plywood-boards", image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=200&h=200&fit=crop", product_count: 350 },
          { id: "6", name: "Fevicol", slug: "fevicol", image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=200&h=200&fit=crop", product_count: 50 },
          { id: "7", name: "Wires", slug: "electrical", image_url: "https://images.unsplash.com/photo-1764866085369-44c7ef1a18f3?w=200&h=200&fit=crop", product_count: 600 },
          { id: "8", name: "Switches\n& Sockets", slug: "switches", image_url: "https://images.unsplash.com/photo-1764866085369-44c7ef1a18f3?w=200&h=200&fit=crop", product_count: 400 },
          { id: "9", name: "Hinges, Channels\n& Handles", slug: "hardware", image_url: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=200&h=200&fit=crop", product_count: 1000 },
          { id: "10", name: "Kitchen Systems\n& Accessories", slug: "kitchen", image_url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=200&h=200&fit=crop", product_count: 200 },
          { id: "11", name: "Wardrobe &\nBed Fittings", slug: "bedroom", image_url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=200&h=200&fit=crop", product_count: 150 },
          { id: "12", name: "Door Locks\n& Hardware", slug: "door-locks", image_url: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=200&h=200&fit=crop", product_count: 300 },
        ],
      },
    },
    {
      type: "FeatureBar",
      id: "feature_bar_001",
      order: 5,
      visible: true,
      data: {
        bg_gradient: "from-[#150726] to-[#2D1B69]",
        features: [
          { title: "LOWEST PRICES", description: "Best quality at best prices", icon: "TrendingUp", color: "#E91E63" },
          { title: "60 MINS DELIVERY", description: "Superfast delivery at your site", icon: "Timer", color: "#00BCD4" },
          { title: "SECURE PAYMENTS", description: "100% safe & secure", icon: "Lock", color: "#7CB518" },
        ],
      },
    },
    {
      type: "ProductCarousel",
      id: "product_carousel_001",
      order: 6,
      visible: true,
      data: {
        title: "Cement",
        products: [
          { id: "cement-acc", name: "ACC Cement 50kg", brand: "ACC", price: 370, mrp: 400, discount: 8, rating: 4.6, review_count: 2100, image_url: "/products/cement/acc.jpg", badge: "Popular", delivery_text: "Tomorrow" },
          { id: "cement-ambuja", name: "Ambuja Cement 50kg", brand: "Ambuja", price: 365, mrp: 395, discount: 8, rating: 4.5, review_count: 1800, image_url: "/products/cement/ambuja.jpg", badge: "Trusted", delivery_text: "Tomorrow" },
          { id: "cement-dalmia", name: "Dalmia Cement RCF Expert 50kg", brand: "Dalmia", price: 355, mrp: 385, discount: 8, rating: 4.5, review_count: 1500, image_url: "/products/cement/dalmia.jpg", delivery_text: "Tomorrow" },
          { id: "cement-jklakshmi", name: "JK Lakshmi Pro+ Cement 50kg", brand: "JK Lakshmi", price: 360, mrp: 390, discount: 8, rating: 4.6, review_count: 1700, image_url: "/products/cement/jk-lakshmi.jpg", badge: "Value", delivery_text: "Tomorrow" },
          { id: "cement-jksuper", name: "JK Super Cement 50kg", brand: "JK Super", price: 350, mrp: 380, discount: 8, rating: 4.4, review_count: 1400, image_url: "/products/cement/jk-super.jpg", delivery_text: "Tomorrow" },
          { id: "cement-jsw", name: "JSW Cement 50kg", brand: "JSW", price: 365, mrp: 395, discount: 8, rating: 4.5, review_count: 1600, image_url: "/products/cement/jsw.jpg", badge: "Deal", delivery_text: "Tomorrow" },
        ],
      },
    },
    {
      type: "ProductGrid",
      id: "product_grid_001",
      order: 7,
      visible: true,
      data: {
        title: "Cement",
        columns: 2,
        products: [
          { id: "cement-mpbirla", name: "MP Birla Samrat Cement 50kg", brand: "MP Birla", price: 355, mrp: 385, discount: 8, rating: 4.5, review_count: 1300, image_url: "/products/cement/mp-birla.jpg", delivery_text: "Tomorrow" },
          { id: "cement-shree", name: "Shree Cement 50kg", brand: "Shree", price: 360, mrp: 390, discount: 8, rating: 4.6, review_count: 1900, image_url: "/products/cement/shree.jpg", badge: "Top Rated", delivery_text: "Tomorrow" },
          { id: "cement-ult", name: "UltraTech Cement OPC 53 Grade 50kg", brand: "UltraTech", price: 385, mrp: 410, discount: 6, rating: 4.7, review_count: 2340, image_url: "/products/cement/ultratech.jpg", badge: "Bestseller", delivery_text: "Tomorrow" },
          { id: "cement-wonder", name: "Wonder Cement 50kg", brand: "Wonder", price: 345, mrp: 375, discount: 8, rating: 4.4, review_count: 1200, image_url: "/products/cement/wonder.jpg", delivery_text: "Tomorrow" },
          { id: "cement-acc2", name: "ACC Cement PPC 50kg", brand: "ACC", price: 365, mrp: 395, discount: 8, rating: 4.6, review_count: 2100, image_url: "/products/cement/acc.jpg", badge: "Value", delivery_text: "Tomorrow" },
          { id: "cement-ambuja2", name: "Ambuja Cement PPC 50kg", brand: "Ambuja", price: 360, mrp: 390, discount: 8, rating: 4.5, review_count: 1800, image_url: "/products/cement/ambuja.jpg", delivery_text: "Tomorrow" },
        ],
      },
    },
  ],
};
