import type { LayoutResponse } from "@/lib/layout-types";

export const STATIC_HOME_LAYOUT: LayoutResponse = {
  version: "1.0",
  screen: "home",
  meta: {
    pincode: "201301",
    city: "New Delhi",
    eta: "60 mins",
    is_serviceable: true,
    user_segment: "all",
  },
  sections: [
    {
      type: "DeliveryBar",
      id: "delivery_bar_001",
      order: 0,
      visible: true,
      data: { eta_minutes: 60, pincode: "201301", city: "New Delhi", is_serviceable: true },
    },
    {
      type: "DispatchBanner",
      id: "dispatch_banner_001",
      order: 1,
      visible: true,
      data: { dispatch_time: "8 AM", dispatch_date: "20 August 2026" },
    },
    {
      type: "PromoBanner",
      id: "promo_banner_001",
      order: 2,
      visible: true,
      data: {
        title: "FREE DELIVERY",
        subtitle: "Free Delivery on next 5 orders",
        badge_text: "(Valid till 31-Jul)",
        badge_color: "#E91E63",
        bg_gradient: "from-[#2D1B69] to-[#4A2D8A]",
        valid_till: "2026-07-31",
      },
    },
    {
      type: "AssuredStrip",
      id: "assured_strip_001",
      order: 3,
      visible: true,
      data: {
        title: "Modit Assured",
        features: [
          { title: "7 Day Replacement", description: "Over & Above Brand Warranty", icon: "RotateCcw", color: "#E91E63" },
          { title: "4 Hour Resolution", description: "On Any Quality Issues", icon: "Clock", color: "#7CB518" },
          { title: "100% Genuine Guarantee", description: "QR Code & Batch Number Verified", icon: "CircleCheck", color: "#7CB518" },
          { title: "Easy Returns", description: "No Questions Asked", icon: "Package", color: "#E91E63" },
        ],
      },
    },
    {
      type: "CategoryGrid",
      id: "category_grid_001",
      order: 4,
      visible: true,
      data: {
        columns: 4,
        categories: [
          { id: "1", name: "Cement", slug: "cement", image_url: "/products/cement/Ambuja Cement.png", product_count: 10 },
          { id: "2", name: "Tiling &\nWaterproof", slug: "tiling-waterproofing", image_url: "/products/tiling/Dr Fixit.png", product_count: 14 },
          { id: "3", name: "Painting", slug: "paint", image_url: "/products/painting/Asian Paint.png", product_count: 34 },
          { id: "4", name: "Lighting", slug: "lighting", image_url: "/products/lighting/Philips AstraSpot Next LED COB light.webp", product_count: 17 },
          { id: "5", name: "Wires &\nCables", slug: "electrical", image_url: "/products/lighting/download-Photoroom (1).png", product_count: 8 },
          { id: "6", name: "Plywood,\nMDF & HDHMR", slug: "plywood-boards", image_url: "/products/painting/Asian Paints Tractor Emulsion, Base White 20 L.png", product_count: 6 },
          { id: "7", name: "Fevicol", slug: "fevicol", image_url: "/products/tiling/Bostik.png", product_count: 5 },
          { id: "8", name: "Hardware", slug: "hardware", image_url: "/products/tiling/Roff T1.png", product_count: 4 },
        ],
      },
    },
    {
      type: "FeatureBar",
      id: "feature_bar_001",
      order: 5,
      visible: true,
      data: {
        bg_gradient: "from-[#150726] to-[#2D1B69]",
        features: [
          { title: "LOWEST PRICES", description: "Best quality at best prices", icon: "TrendingUp", color: "#E91E63" },
          { title: "60 MINS DELIVERY", description: "Superfast delivery at your site", icon: "Timer", color: "#00BCD4" },
          { title: "SECURE PAYMENTS", description: "100% safe & secure", icon: "Lock", color: "#7CB518" },
        ],
      },
    },
    {
      type: "ProductCarousel",
      id: "product_carousel_cement",
      order: 6,
      visible: true,
      data: {
        title: "Cement",
        products: [
          { id: "cement-acc", name: "ACC Cement 50kg", brand: "ACC", price: 370, mrp: 400, discount: 8, rating: 4.6, review_count: 2100, image_url: "/products/cement/ACC Cement.png", badge: "Popular", delivery_text: "Tomorrow" },
          { id: "cement-ambuja", name: "Ambuja Cement 50kg", brand: "Ambuja", price: 365, mrp: 395, discount: 8, rating: 4.5, review_count: 1800, image_url: "/products/cement/Ambuja Cement.png", badge: "Trusted", delivery_text: "Tomorrow" },
          { id: "cement-dalmia", name: "Dalmia Cement 50kg", brand: "Dalmia", price: 355, mrp: 385, discount: 8, rating: 4.5, review_count: 1500, image_url: "/products/cement/Dalmia Cement.png", delivery_text: "Tomorrow" },
          { id: "cement-jklakshmi", name: "JK Lakshmi Pro+ Cement 50kg", brand: "JK Lakshmi", price: 360, mrp: 390, discount: 8, rating: 4.6, review_count: 1700, image_url: "/products/cement/JK Lakshmi Pro Cement.png", badge: "Value", delivery_text: "Tomorrow" },
          { id: "cement-jksuper", name: "JK Super Cement 50kg", brand: "JK Super", price: 350, mrp: 380, discount: 8, rating: 4.4, review_count: 1400, image_url: "/products/cement/JK Super Cement.png", delivery_text: "Tomorrow" },
          { id: "cement-jsw", name: "JSW Cement 50kg", brand: "JSW", price: 365, mrp: 395, discount: 8, rating: 4.5, review_count: 1600, image_url: "/products/cement/JSW Cement.png", badge: "Deal", delivery_text: "Tomorrow" },
        ],
      },
    },
    {
      type: "ProductCarousel",
      id: "product_carousel_painting",
      order: 7,
      visible: true,
      data: {
        title: "Painting",
        products: [
          { id: "paint-asian-apex", name: "Asian Paints Apex, Base White", brand: "Asian Paints", price: 2400, mrp: 3100, discount: 23, rating: 4.6, review_count: 4230, image_url: "/products/painting/Asian Paints Apex, Base White.png", badge: "Bestseller", delivery_text: "Tomorrow" },
          { id: "paint-asian-royale", name: "Asian Paints Royale Luxury Emulsion", brand: "Asian Paints", price: 3200, mrp: 4000, discount: 20, rating: 4.7, review_count: 3100, image_url: "/products/painting/Asian Paints Royale Luxury Emulsion, Base White.png", badge: "Premium", delivery_text: "Tomorrow" },
          { id: "paint-asian-tractor", name: "Asian Paints Tractor Emulsion 20L", brand: "Asian Paints", price: 1800, mrp: 2200, discount: 18, rating: 4.5, review_count: 5200, image_url: "/products/painting/Asian Paints Tractor Emulsion, Base White 20 L.png", delivery_text: "Tomorrow" },
          { id: "paint-asian-ace", name: "Asian Paints Ace, Base White", brand: "Asian Paints", price: 1950, mrp: 2400, discount: 19, rating: 4.5, review_count: 2800, image_url: "/products/painting/Asian Paints Ace, Base White.png", delivery_text: "Tomorrow" },
          { id: "paint-birla-putty", name: "Birla Wall Putty 1kg", brand: "Birla White", price: 180, mrp: 210, discount: 14, rating: 4.4, review_count: 3400, image_url: "/products/painting/Birla Putty.png", badge: "Value", delivery_text: "Tomorrow" },
          { id: "paint-asian-putty", name: "Asian Paints TruCare Acrylic Wall Putty", brand: "Asian Paints", price: 350, mrp: 420, discount: 17, rating: 4.5, review_count: 1800, image_url: "/products/painting/Asian Paints TruCare Acrylic Wall Putty.png", delivery_text: "Tomorrow" },
        ],
      },
    },
    {
      type: "ProductCarousel",
      id: "product_carousel_lighting",
      order: 8,
      visible: true,
      data: {
        title: "Lighting",
        products: [
          { id: "light-philips-cob", name: "Philips AstraSpot Next LED COB Light", brand: "Philips", price: 899, mrp: 1200, discount: 25, rating: 4.6, review_count: 1200, image_url: "/products/lighting/Philips AstraSpot Next LED COB light.webp", badge: "Popular", delivery_text: "Tomorrow" },
          { id: "light-philips-3in1", name: "Philips Astraspot 3-In-1 COB Light", brand: "Philips", price: 1499, mrp: 1999, discount: 25, rating: 4.7, review_count: 890, image_url: "/products/lighting/Philips Astraspot 3-In-1 COB Light, Tunable, White.webp", badge: "Premium", delivery_text: "Tomorrow" },
          { id: "light-philips-surface", name: "Philips Full Glow LED Surface Light", brand: "Philips", price: 699, mrp: 899, discount: 22, rating: 4.5, review_count: 1500, image_url: "/products/lighting/Philips Full Glow LED Surface Light, Round.webp", delivery_text: "Tomorrow" },
          { id: "light-philips-strip", name: "Philips EvenGlow LED Strip Light 5m", brand: "Philips", price: 1299, mrp: 1699, discount: 24, rating: 4.4, review_count: 780, image_url: "/products/lighting/Philips EvenGlow LED Strip Light, 5m.webp", delivery_text: "Tomorrow" },
          { id: "light-philips-tube", name: "Philips Slimline Ultra LED Tube Light 20W", brand: "Philips", price: 549, mrp: 749, discount: 27, rating: 4.6, review_count: 2100, image_url: "/products/lighting/Philips Slimline Ultra LED Tube Light, 20W.webp", badge: "Deal", delivery_text: "Tomorrow" },
          { id: "light-philips-rope", name: "Philips Marathon Ultra LED Rope Light 50m", brand: "Philips", price: 1899, mrp: 2499, discount: 24, rating: 4.3, review_count: 560, image_url: "/products/lighting/Philips Marathon Ultra LED Rope Light, 50m (Strip Light), Warm White.webp", delivery_text: "Tomorrow" },
        ],
      },
    },
    {
      type: "ProductGrid",
      id: "product_grid_tiling",
      order: 9,
      visible: true,
      data: {
        title: "Tiling & Waterproofing",
        columns: 2,
        products: [
          { id: "tile-drfixit", name: "Dr Fixit Waterproofing Solution", brand: "Dr Fixit", price: 850, mrp: 1100, discount: 23, rating: 4.6, review_count: 2200, image_url: "/products/tiling/Dr Fixit.png", badge: "Bestseller", delivery_text: "Tomorrow" },
          { id: "tile-kajaria-1", name: "Kajaria Adhesives Tiling", brand: "Kajaria", price: 420, mrp: 550, discount: 24, rating: 4.5, review_count: 1800, image_url: "/products/tiling/Kajaria Adhesives Tiling.png", delivery_text: "Tomorrow" },
          { id: "tile-roff", name: "Roff Tiling Adhesive", brand: "Roff", price: 480, mrp: 600, discount: 20, rating: 4.5, review_count: 1500, image_url: "/products/tiling/Roff T1.png", badge: "Trusted", delivery_text: "Tomorrow" },
          { id: "tile-weber", name: "Weber Tiling Solution", brand: "Weber", price: 390, mrp: 500, discount: 22, rating: 4.4, review_count: 1200, image_url: "/products/tiling/Weber.png", delivery_text: "Tomorrow" },
          { id: "tile-apex", name: "Apex Endura Waterproofing", brand: "Apex", price: 720, mrp: 900, discount: 20, rating: 4.5, review_count: 980, image_url: "/products/tiling/Apex Endura.png", delivery_text: "Tomorrow" },
          { id: "tile-bostik", name: "Bostik Tiling Adhesive", brand: "Bostik", price: 550, mrp: 700, discount: 21, rating: 4.4, review_count: 870, image_url: "/products/tiling/Bostik.png", delivery_text: "Tomorrow" },
        ],
      },
    },
  ],
};
